package com.Contum.Integration.models;

public class order2s extends sendEnvelopeBase{

	public static String r1PhoneMobile;
	public static String r2PhoneMobile;

	
	
	
	public static String getR1PhoneMobile() {
		return r1PhoneMobile;
	}



	public static void setR1PhoneMobile(String r1PhoneMobile) {
		order2s.r1PhoneMobile = r1PhoneMobile;
	}



	public static String getR2PhoneMobile() {
		return r2PhoneMobile;
	}

	
	static void setR2PhoneMobile(String r2PhoneMobile) {
		order2s.r2PhoneMobile = r2PhoneMobile;
	}

	public static void setParameters(String envelopeName, String r1Email, String r1FirstName, String r1LastName, String r1phone,
			String r2Email, String r2FirstName, String r2LastName, String r2phone) {
		setEnvelopeName(envelopeName);
		setR1Email(r1Email);
		setR1FirstName(r1FirstName);
		setR1LastName(r1LastName);
		setR1PhoneMobile(r1phone);
		setR2Email(r2Email);
		setR2FirstName(r2FirstName);
		setR2LastName(r2LastName);
		setR2PhoneMobile(r2phone);
		
	}
		


	public static String getRequest() {
		return "{\r\n"
				+ "    \"SspFileIds\": [\r\n"
				+ "        \""+sspFileId+"\"\r\n"
				+ "    ],\r\n"
				+ "    \"SendEnvelopeDescription\": {\r\n"
				+ "        \"Name\": \""+envelopeName+"\",\r\n"
				+ "        \"EmailSubject\": \"Please sign the enclosed envelope\",\r\n"
				+ "        \"EmailBody\": \"Dear #RecipientFirstName# #RecipientLastName#\\n\\n#PersonalMessage#\\n\\nPlease sign the envelope #EnvelopeName#\\n\\nEnvelope will expire at #ExpirationDate#\",\r\n"
				+ "        \"DisplayedEmailSender\": \"\",\r\n"
				+ "        \"EnableReminders\": true,\r\n"
				+ "        \"FirstReminderDayAmount\": 5,\r\n"
				+ "        \"RecurrentReminderDayAmount\": 3,\r\n"
				+ "        \"BeforeExpirationDayAmount\": 3,\r\n"
				+ "        \"ExpirationInSecondsAfterSending\": 2419200,\r\n"
				+ "        \"CallbackUrl\": \"\",\r\n"
				+ "        \"StatusUpdateCallbackUrl\": \"\",\r\n"
				+ "        \"LockFormFieldsAtEnvelopeFinish\": false,\r\n"
				+ "        \"Steps\": [\r\n"
				+ "            {\r\n"
				+ "                \"OrderIndex\": 1,\r\n"
				+ "                \"Recipients\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"Email\": \""+r1Email+"\",\r\n"
				+ "                        \"FirstName\": \""+r1FirstName+"\",\r\n"
				+ "                        \"LastName\": \""+r1LastName+"\",\r\n"
				+ "                        \"LanguageCode\": \"en\",\r\n"
				+ "                        \"EmailBodyExtra\": \"\",\r\n"
				+ "                        \"DisableEmail\": false,\r\n"
				+ "                        \"AddAndroidAppLink\": false,\r\n"
				+ "                        \"AddIosAppLink\": false,\r\n"
				+ "                        \"AddWindowsAppLink\": false,\r\n"
				+ "                        \"AllowDelegation\": true,\r\n"
				+ "                        \"AllowAccessFinishedWorkstep\": false,\r\n"
				+ "                        \"SkipExternalDataValidation\": false,\r\n"
				+ "                        \"AuthenticationMethods\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"Method\": \"Sms\",\r\n"
				+ "                                \"Parameter\": \""+r1PhoneMobile+"\"\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"EmailBodyExtra\": \"\",\r\n"
				+ "                \"RecipientType\": \"Signer\",\r\n"
				+ "                \"WorkstepConfiguration\": {\r\n"
				+ "                    \"WorkstepLabel\": \"Megrendelőlap3.pdf\",\r\n"
				+ "                    \"SmallTextZoomFactorPercent\": 100,\r\n"
				+ "                    \"FinishAction\": {\r\n"
				+ "                        \"ServerActions\": [],\r\n"
				+ "                        \"ClientActions\": []\r\n"
				+ "                    },\r\n"
				+ "                    \"ReceiverInformation\": {\r\n"
				+ "                        \"UserInformation\": {\r\n"
				+ "                            \"FirstName\": \""+r1FirstName+"\",\r\n"
				+ "                            \"LastName\": \""+r1LastName+"\",\r\n"
				+ "                            \"EMail\": \""+r1Email+"\"\r\n"
				+ "                        },\r\n"
				+ "                        \"TransactionCodePushPluginData\": []\r\n"
				+ "                    },\r\n"
				+ "                    \"SenderInformation\": {\r\n"
				+ "                        \"UserInformation\": {\r\n"
				+ "                            \"FirstName\": \""+r2FirstName+"\",\r\n"
				+ "                            \"LastName\": \""+r2LastName+"\",\r\n"
				+ "                            \"EMail\": \""+r2Email+"\"\r\n"
				+ "                        }\r\n"
				+ "                    },\r\n"
				+ "                    \"TransactionCodeConfigurations\": [],\r\n"
				+ "                    \"SignatureConfigurations\": [],\r\n"
				+ "                    \"ViewerPreferences\": {\r\n"
				+ "                        \"FinishWorkstepOnOpen\": false,\r\n"
				+ "                        \"VisibleAreaOptions\": {\r\n"
				+ "                            \"AllowedDomain\": \"*\",\r\n"
				+ "                            \"Enabled\": false\r\n"
				+ "                        }\r\n"
				+ "                    },\r\n"
				+ "                    \"ResourceUris\": {\r\n"
				+ "                        \"DelegationUri\": \"https://demo.esignanywhere.net/Resource/Delegate\"\r\n"
				+ "                    },\r\n"
				+ "                    \"AdditionalClientWorkstepInformation\": \"<metaData />\",\r\n"
				+ "                    \"AuditingToolsConfiguration\": {\r\n"
				+ "                        \"WriteAuditTrail\": false,\r\n"
				+ "                        \"NotificationConfiguration\": {}\r\n"
				+ "                    },\r\n"
				+ "                    \"Policy\": {\r\n"
				+ "                        \"GeneralPolicies\": {\r\n"
				+ "                            \"AllowSaveDocument\": true,\r\n"
				+ "                            \"AllowSaveAuditTrail\": true,\r\n"
				+ "                            \"AllowRotatingPages\": false,\r\n"
				+ "                            \"AllowEmailDocument\": true,\r\n"
				+ "                            \"AllowPrintDocument\": true,\r\n"
				+ "                            \"AllowFinishWorkstep\": true,\r\n"
				+ "                            \"AllowRejectWorkstep\": true,\r\n"
				+ "                            \"AllowRejectWorkstepDelegation\": true,\r\n"
				+ "                            \"AllowUndoLastAction\": false,\r\n"
				+ "                            \"AllowAdhocPdfAttachments\": false,\r\n"
				+ "                            \"AllowAdhocSignatures\": false,\r\n"
				+ "                            \"AllowAdhocStampings\": false,\r\n"
				+ "                            \"AllowAdhocFreeHandAnnotations\": false,\r\n"
				+ "                            \"AllowAdhocTypewriterAnnotations\": false,\r\n"
				+ "                            \"AllowAdhocPictureAnnotations\": false,\r\n"
				+ "                            \"AllowAdhocPdfPageAppending\": false\r\n"
				+ "                        },\r\n"
				+ "                        \"WorkstepTasks\": {\r\n"
				+ "                            \"PictureAnnotationMinResolution\": 0,\r\n"
				+ "                            \"PictureAnnotationMaxResolution\": 0,\r\n"
				+ "                            \"PictureAnnotationColorDepth\": \"Color16M\",\r\n"
				+ "                            \"SequenceMode\": \"NoSequenceEnforced\",\r\n"
				+ "                            \"PositionUnits\": \"PdfUnits\",\r\n"
				+ "                            \"ReferenceCorner\": \"Lower_Left\",\r\n"
				+ "                            \"Tasks\": [\r\n"
				+ "                                {\r\n"
				+ "                                    \"PageNumber\": 1,\r\n"
				+ "                                    \"TextAlign\": \"Left\",\r\n"
				+ "                                    \"Position\": {\r\n"
				+ "                                        \"PositionX\": 103.0,\r\n"
				+ "                                        \"PositionY\": 83.0\r\n"
				+ "                                    },\r\n"
				+ "                                    \"DefaultText\": \"##ReceiverFirstName## ##ReceiverLastName##\",\r\n"
				+ "                                    \"TextFormat\": \"\",\r\n"
				+ "                                    \"DefaultTextType\": \"FullName\",\r\n"
				+ "                                    \"FontSettings\": {\r\n"
				+ "                                        \"Id\": \"f38d9f60-660e-406c-a643-146dbefe63c4\",\r\n"
				+ "                                        \"TextColor\": {\r\n"
				+ "                                            \"A\": 255,\r\n"
				+ "                                            \"R\": 0,\r\n"
				+ "                                            \"G\": 0,\r\n"
				+ "                                            \"B\": 0\r\n"
				+ "                                        },\r\n"
				+ "                                        \"Name\": \"Times New Roman\",\r\n"
				+ "                                        \"Size\": 11.0,\r\n"
				+ "                                        \"IsBold\": false,\r\n"
				+ "                                        \"IsItalic\": false\r\n"
				+ "                                    },\r\n"
				+ "                                    \"IsEditablePosition\": false,\r\n"
				+ "                                    \"IsEditableDefaultText\": false,\r\n"
				+ "                                    \"IsEditableFontSettings\": false,\r\n"
				+ "                                    \"IsRequired\": false,\r\n"
				+ "                                    \"Id\": \"adbb52c2-d669-4c4a-86ba-1090f29b605c\",\r\n"
				+ "                                    \"DocRefNumber\": 1,\r\n"
				+ "                                    \"DiscriminatorType\": \"TypewriterAnnotation\"\r\n"
				+ "                                },\r\n"
				+ "                                {\r\n"
				+ "                                    \"PageNumber\": 1,\r\n"
				+ "                                    \"TextAlign\": \"Left\",\r\n"
				+ "                                    \"Position\": {\r\n"
				+ "                                        \"PositionX\": 103.0,\r\n"
				+ "                                        \"PositionY\": 65.0\r\n"
				+ "                                    },\r\n"
				+ "                                    \"DefaultText\": \"##ClientTime##\",\r\n"
				+ "                                    \"TextFormat\": \"dd/MM/yyyy\",\r\n"
				+ "                                    \"DefaultTextType\": \"DateTime\",\r\n"
				+ "                                    \"FontSettings\": {\r\n"
				+ "                                        \"Id\": \"f38d9f60-660e-406c-a643-146dbefe63c4\",\r\n"
				+ "                                        \"TextColor\": {\r\n"
				+ "                                            \"A\": 255,\r\n"
				+ "                                            \"R\": 0,\r\n"
				+ "                                            \"G\": 0,\r\n"
				+ "                                            \"B\": 0\r\n"
				+ "                                        },\r\n"
				+ "                                        \"Name\": \"Times New Roman\",\r\n"
				+ "                                        \"Size\": 11.0,\r\n"
				+ "                                        \"IsBold\": false,\r\n"
				+ "                                        \"IsItalic\": false\r\n"
				+ "                                    },\r\n"
				+ "                                    \"IsEditablePosition\": false,\r\n"
				+ "                                    \"IsEditableDefaultText\": false,\r\n"
				+ "                                    \"IsEditableFontSettings\": false,\r\n"
				+ "                                    \"IsRequired\": false,\r\n"
				+ "                                    \"Id\": \"e7864379-656b-49d5-b99e-69cb09951932\",\r\n"
				+ "                                    \"DocRefNumber\": 1,\r\n"
				+ "                                    \"DiscriminatorType\": \"TypewriterAnnotation\"\r\n"
				+ "                                },\r\n"
				+ "                                {\r\n"
				+ "                                    \"Forms\": [\r\n"
				+ "                                        {\r\n"
				+ "                                            \"IsRequired\": true,\r\n"
				+ "                                            \"Id\": \"TextBox_CustomerName\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 162.0,\r\n"
				+ "                                                \"PositionY\": 676.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 20.0,\r\n"
				+ "                                                \"Width\": 358.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"TextBox\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"IsRequired\": true,\r\n"
				+ "                                            \"Id\": \"TextBox_CustomerAddress\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 163.0,\r\n"
				+ "                                                \"PositionY\": 653.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 20.0,\r\n"
				+ "                                                \"Width\": 358.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"TextBox\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"IsRequired\": true,\r\n"
				+ "                                            \"Id\": \"TextBox_CustomerMobile\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 140.0,\r\n"
				+ "                                                \"PositionY\": 631.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 20.0,\r\n"
				+ "                                                \"Width\": 382.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"TextBox\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"IsRequired\": true,\r\n"
				+ "                                            \"Id\": \"TextBox_CustomerEmail\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 109.0,\r\n"
				+ "                                                \"PositionY\": 607.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 20.0,\r\n"
				+ "                                                \"Width\": 412.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"TextBox\"\r\n"
				+ "                                        }\r\n"
				+ "                                    ],\r\n"
				+ "                                    \"IsRequired\": true,\r\n"
				+ "                                    \"Id\": \"29a2f60c-98c5-42b0-ad64-71319debae9b\",\r\n"
				+ "                                    \"DisplayName\": \"\",\r\n"
				+ "                                    \"DocRefNumber\": 1,\r\n"
				+ "                                    \"DiscriminatorType\": \"FormGroup\"\r\n"
				+ "                                },\r\n"
				+ "                                {\r\n"
				+ "                                    \"Forms\": [\r\n"
				+ "                                        {\r\n"
				+ "                                            \"RadioButtonGroupId\": \"RadioButton_USB64GB\",\r\n"
				+ "                                            \"IsRequired\": false,\r\n"
				+ "                                            \"Id\": \"0\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 266.0,\r\n"
				+ "                                                \"PositionY\": 533.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 20.0,\r\n"
				+ "                                                \"Width\": 20.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"RadioButton\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"IsRequired\": false,\r\n"
				+ "                                            \"Items\": [],\r\n"
				+ "                                            \"Id\": \"ComboBox_USB64GB\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 355.0,\r\n"
				+ "                                                \"PositionY\": 530.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 26.0,\r\n"
				+ "                                                \"Width\": 113.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"ComboBox\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"RadioButtonGroupId\": \"RadioButton_USB128GB\",\r\n"
				+ "                                            \"IsRequired\": false,\r\n"
				+ "                                            \"Id\": \"0\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 265.0,\r\n"
				+ "                                                \"PositionY\": 505.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 20.0,\r\n"
				+ "                                                \"Width\": 20.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"RadioButton\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"IsRequired\": false,\r\n"
				+ "                                            \"Items\": [],\r\n"
				+ "                                            \"Id\": \"ComboBox_USB128GB\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 356.0,\r\n"
				+ "                                                \"PositionY\": 505.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 22.0,\r\n"
				+ "                                                \"Width\": 112.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"ComboBox\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"RadioButtonGroupId\": \"RadioButton_SSD512GB\",\r\n"
				+ "                                            \"IsRequired\": false,\r\n"
				+ "                                            \"Id\": \"0\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 265.0,\r\n"
				+ "                                                \"PositionY\": 478.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 20.0,\r\n"
				+ "                                                \"Width\": 20.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"RadioButton\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"IsRequired\": false,\r\n"
				+ "                                            \"Items\": [],\r\n"
				+ "                                            \"Id\": \"ComboBox_SSD512GB\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 356.0,\r\n"
				+ "                                                \"PositionY\": 476.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 25.0,\r\n"
				+ "                                                \"Width\": 110.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"ComboBox\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"RadioButtonGroupId\": \"RadioButton_SSD1TB\",\r\n"
				+ "                                            \"IsRequired\": false,\r\n"
				+ "                                            \"Id\": \"0\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 265.0,\r\n"
				+ "                                                \"PositionY\": 452.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 20.0,\r\n"
				+ "                                                \"Width\": 20.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"RadioButton\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"IsRequired\": false,\r\n"
				+ "                                            \"Items\": [],\r\n"
				+ "                                            \"Id\": \"ComboBox_SSD1TB\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 355.0,\r\n"
				+ "                                                \"PositionY\": 447.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 26.0,\r\n"
				+ "                                                \"Width\": 112.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"ComboBox\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"RadioButtonGroupId\": \"RadioButton_HDD512GB\",\r\n"
				+ "                                            \"IsRequired\": false,\r\n"
				+ "                                            \"Id\": \"0\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 265.0,\r\n"
				+ "                                                \"PositionY\": 422.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 20.0,\r\n"
				+ "                                                \"Width\": 20.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"RadioButton\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"IsRequired\": false,\r\n"
				+ "                                            \"Items\": [],\r\n"
				+ "                                            \"Id\": \"ComboBox_HDD512GB\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 356.0,\r\n"
				+ "                                                \"PositionY\": 420.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 24.0,\r\n"
				+ "                                                \"Width\": 111.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"ComboBox\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"RadioButtonGroupId\": \"RadioButton_HDD1TB\",\r\n"
				+ "                                            \"IsRequired\": false,\r\n"
				+ "                                            \"Id\": \"0\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 264.0,\r\n"
				+ "                                                \"PositionY\": 393.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 20.0,\r\n"
				+ "                                                \"Width\": 20.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"RadioButton\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"IsRequired\": false,\r\n"
				+ "                                            \"Items\": [],\r\n"
				+ "                                            \"Id\": \"ComboBox_HDD1TB\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 356.0,\r\n"
				+ "                                                \"PositionY\": 391.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 26.0,\r\n"
				+ "                                                \"Width\": 109.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"ComboBox\"\r\n"
				+ "                                        }\r\n"
				+ "                                    ],\r\n"
				+ "                                    \"IsRequired\": false,\r\n"
				+ "                                    \"Id\": \"12e62cd9-6e9d-4e33-acc8-e5773c47ab73\",\r\n"
				+ "                                    \"DisplayName\": \"\",\r\n"
				+ "                                    \"DocRefNumber\": 1,\r\n"
				+ "                                    \"DiscriminatorType\": \"FormGroup\"\r\n"
				+ "                                },\r\n"
				+ "                                {\r\n"
				+ "                                    \"Forms\": [\r\n"
				+ "                                        {\r\n"
				+ "                                            \"IsRequired\": true,\r\n"
				+ "                                            \"RequiredEvalPolicy\": \"IsChecked\",\r\n"
				+ "                                            \"Id\": \"CheckBox_b3051d21-84b4-6d3f-04bf-628688694419\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 72.0,\r\n"
				+ "                                                \"PositionY\": 349.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 20.0,\r\n"
				+ "                                                \"Width\": 20.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"CheckBox\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"IsRequired\": true,\r\n"
				+ "                                            \"RequiredEvalPolicy\": \"IsChecked\",\r\n"
				+ "                                            \"Id\": \"CheckBox_198c738c-6388-ddc4-f119-f9bfe63716c9\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 72.0,\r\n"
				+ "                                                \"PositionY\": 326.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 20.0,\r\n"
				+ "                                                \"Width\": 20.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"CheckBox\"\r\n"
				+ "                                        }\r\n"
				+ "                                    ],\r\n"
				+ "                                    \"IsRequired\": true,\r\n"
				+ "                                    \"Id\": \"16c9778d-bbe1-48af-b8f5-d0a8333c452e\",\r\n"
				+ "                                    \"DisplayName\": \"\",\r\n"
				+ "                                    \"DocRefNumber\": 1,\r\n"
				+ "                                    \"DiscriminatorType\": \"FormGroup\"\r\n"
				+ "                                },\r\n"
				+ "                                {\r\n"
				+ "                                    \"Forms\": [\r\n"
				+ "                                        {\r\n"
				+ "                                            \"IsRequired\": false,\r\n"
				+ "                                            \"RequiredEvalPolicy\": \"None\",\r\n"
				+ "                                            \"Id\": \"CheckBox_2ce4c1c0-1a65-cdf5-6a26-b73063c3ffd5\",\r\n"
				+ "                                            \"PositionPage\": 1,\r\n"
				+ "                                            \"DocRefNumber\": 1,\r\n"
				+ "                                            \"Position\": {\r\n"
				+ "                                                \"PositionX\": 72.0,\r\n"
				+ "                                                \"PositionY\": 303.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"Size\": {\r\n"
				+ "                                                \"Height\": 20.0,\r\n"
				+ "                                                \"Width\": 20.0\r\n"
				+ "                                            },\r\n"
				+ "                                            \"DiscriminatorType\": \"CheckBox\"\r\n"
				+ "                                        }\r\n"
				+ "                                    ],\r\n"
				+ "                                    \"IsRequired\": false,\r\n"
				+ "                                    \"Id\": \"c7d9a330-83e7-48f0-bb4b-800982403d48\",\r\n"
				+ "                                    \"DisplayName\": \"\",\r\n"
				+ "                                    \"DocRefNumber\": 1,\r\n"
				+ "                                    \"DiscriminatorType\": \"FormGroup\"\r\n"
				+ "                                },\r\n"
				+ "                                {\r\n"
				+ "                                    \"PositionPage\": 1,\r\n"
				+ "                                    \"Position\": {\r\n"
				+ "                                        \"PositionX\": 40,\r\n"
				+ "                                        \"PositionY\": 131.9\r\n"
				+ "                                    },\r\n"
				+ "                                    \"Size\": {\r\n"
				+ "                                        \"Height\": 80.0,\r\n"
				+ "                                        \"Width\": 190.0\r\n"
				+ "                                    },\r\n"
				+ "                                    \"AdditionalParameters\": [\r\n"
				+ "                                        {\r\n"
				+ "                                            \"Key\": \"enabled\",\r\n"
				+ "                                            \"Value\": \"1\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"Key\": \"positioning\",\r\n"
				+ "                                            \"Value\": \"onPage\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"Key\": \"req\",\r\n"
				+ "                                            \"Value\": \"1\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"Key\": \"fd\",\r\n"
				+ "                                            \"Value\": \"\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"Key\": \"fd_dateformat\",\r\n"
				+ "                                            \"Value\": \"dd-MM-yyyy HH:mm:ss\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"Key\": \"fd_timezone\",\r\n"
				+ "                                            \"Value\": \"datetimeutc\"\r\n"
				+ "                                        }\r\n"
				+ "                                    ],\r\n"
				+ "                                    \"AllowedSignatureTypes\": [\r\n"
				+ "                                        {\r\n"
				+ "                                            \"AllowedCapturingMethod\": \"Click2Sign\",\r\n"
				+ "                                            \"Id\": \"bfc12f6a-a4d4-461d-a991-cd0e9bcfd65f\",\r\n"
				+ "                                            \"DiscriminatorType\": \"SigTypeClick2Sign\",\r\n"
				+ "                                            \"Preferred\": false,\r\n"
				+ "                                            \"StampImprintConfiguration\": {\r\n"
				+ "                                                \"DisplayExtraInformation\": true,\r\n"
				+ "                                                \"DisplayEmail\": true,\r\n"
				+ "                                                \"DisplayIp\": true,\r\n"
				+ "                                                \"DisplayName\": true,\r\n"
				+ "                                                \"DisplaySignatureDate\": true,\r\n"
				+ "                                                \"FontFamily\": \"Times New Roman\",\r\n"
				+ "                                                \"FontSize\": 11.0\r\n"
				+ "                                            }\r\n"
				+ "                                        }\r\n"
				+ "                                    ],\r\n"
				+ "                                    \"UseTimestamp\": false,\r\n"
				+ "                                    \"IsRequired\": true,\r\n"
				+ "                                    \"Id\": \"1#XyzmoDuplicateIdSeperator#Signature_0af5c3bd-0423-98f6-2f2e-bce1d0c990d6\",\r\n"
				+ "                                    \"DisplayName\": \"\",\r\n"
				+ "                                    \"DocRefNumber\": 1,\r\n"
				+ "                                    \"DiscriminatorType\": \"Signature\"\r\n"
				+ "                                }\r\n"
				+ "                            ]\r\n"
				+ "                        }\r\n"
				+ "                    },\r\n"
				+ "                    \"Navigation\": {\r\n"
				+ "                        \"HyperLinks\": [],\r\n"
				+ "                        \"Links\": [],\r\n"
				+ "                        \"LinkTargets\": []\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                \"DocumentOptions\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"DocumentReference\": \"1\",\r\n"
				+ "                        \"IsHidden\": false\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"UseDefaultAgreements\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"OrderIndex\": 2,\r\n"
				+ "                \"Recipients\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"Email\": \""+r2Email+"\",\r\n"
				+ "                        \"FirstName\": \""+r2FirstName+"\",\r\n"
				+ "                        \"LastName\": \""+r2LastName+"\",\r\n"
				+ "                        \"LanguageCode\": \"en\",\r\n"
				+ "                        \"EmailBodyExtra\": \"\",\r\n"
				+ "                        \"DisableEmail\": false,\r\n"
				+ "                        \"AddAndroidAppLink\": false,\r\n"
				+ "                        \"AddIosAppLink\": false,\r\n"
				+ "                        \"AddWindowsAppLink\": false,\r\n"
				+ "                        \"AllowDelegation\": true,\r\n"
				+ "                        \"AllowAccessFinishedWorkstep\": false,\r\n"
				+ "                        \"SkipExternalDataValidation\": false,\r\n"
				+ "                        \"AuthenticationMethods\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"Method\": \"Sms\",\r\n"
				+ "                                \"Parameter\": \""+r2PhoneMobile+"\"\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"EmailBodyExtra\": \"\",\r\n"
				+ "                \"RecipientType\": \"Signer\",\r\n"
				+ "                \"WorkstepConfiguration\": {\r\n"
				+ "                    \"WorkstepLabel\": \"Megrendelőlap3.pdf\",\r\n"
				+ "                    \"SmallTextZoomFactorPercent\": 100,\r\n"
				+ "                    \"FinishAction\": {\r\n"
				+ "                        \"ServerActions\": [],\r\n"
				+ "                        \"ClientActions\": []\r\n"
				+ "                    },\r\n"
				+ "                    \"ReceiverInformation\": {\r\n"
				+ "                        \"UserInformation\": {\r\n"
				+ "                            \"FirstName\": \""+r1FirstName+"\",\r\n"
				+ "                            \"LastName\": \""+r2LastName+"\",\r\n"
				+ "                            \"EMail\": \""+r2Email+"\"\r\n"
				+ "                        },\r\n"
				+ "                        \"TransactionCodePushPluginData\": []\r\n"
				+ "                    },\r\n"
				+ "                    \"SenderInformation\": {\r\n"
				+ "                        \"UserInformation\": {\r\n"
				+ "                            \"FirstName\": \""+r2FirstName+"\",\r\n"
				+ "                            \"LastName\": \""+r2LastName+"\",\r\n"
				+ "                            \"EMail\": \""+r2Email+"\"\r\n"
				+ "                        }\r\n"
				+ "                    },\r\n"
				+ "                    \"TransactionCodeConfigurations\": [],\r\n"
				+ "                    \"SignatureConfigurations\": [],\r\n"
				+ "                    \"ViewerPreferences\": {\r\n"
				+ "                        \"FinishWorkstepOnOpen\": false,\r\n"
				+ "                        \"VisibleAreaOptions\": {\r\n"
				+ "                            \"AllowedDomain\": \"*\",\r\n"
				+ "                            \"Enabled\": false\r\n"
				+ "                        }\r\n"
				+ "                    },\r\n"
				+ "                    \"ResourceUris\": {\r\n"
				+ "                        \"DelegationUri\": \"https://demo.esignanywhere.net/Resource/Delegate\"\r\n"
				+ "                    },\r\n"
				+ "                    \"AdditionalClientWorkstepInformation\": \"<metaData />\",\r\n"
				+ "                    \"AuditingToolsConfiguration\": {\r\n"
				+ "                        \"WriteAuditTrail\": false,\r\n"
				+ "                        \"NotificationConfiguration\": {}\r\n"
				+ "                    },\r\n"
				+ "                    \"Policy\": {\r\n"
				+ "                        \"GeneralPolicies\": {\r\n"
				+ "                            \"AllowSaveDocument\": true,\r\n"
				+ "                            \"AllowSaveAuditTrail\": true,\r\n"
				+ "                            \"AllowRotatingPages\": false,\r\n"
				+ "                            \"AllowEmailDocument\": true,\r\n"
				+ "                            \"AllowPrintDocument\": true,\r\n"
				+ "                            \"AllowFinishWorkstep\": true,\r\n"
				+ "                            \"AllowRejectWorkstep\": true,\r\n"
				+ "                            \"AllowRejectWorkstepDelegation\": true,\r\n"
				+ "                            \"AllowUndoLastAction\": false,\r\n"
				+ "                            \"AllowAdhocPdfAttachments\": false,\r\n"
				+ "                            \"AllowAdhocSignatures\": false,\r\n"
				+ "                            \"AllowAdhocStampings\": false,\r\n"
				+ "                            \"AllowAdhocFreeHandAnnotations\": false,\r\n"
				+ "                            \"AllowAdhocTypewriterAnnotations\": false,\r\n"
				+ "                            \"AllowAdhocPictureAnnotations\": false,\r\n"
				+ "                            \"AllowAdhocPdfPageAppending\": false\r\n"
				+ "                        },\r\n"
				+ "                        \"WorkstepTasks\": {\r\n"
				+ "                            \"PictureAnnotationMinResolution\": 0,\r\n"
				+ "                            \"PictureAnnotationMaxResolution\": 0,\r\n"
				+ "                            \"PictureAnnotationColorDepth\": \"Color16M\",\r\n"
				+ "                            \"SequenceMode\": \"NoSequenceEnforced\",\r\n"
				+ "                            \"PositionUnits\": \"PdfUnits\",\r\n"
				+ "                            \"ReferenceCorner\": \"Lower_Left\",\r\n"
				+ "                            \"Tasks\": [\r\n"
				+ "                                {\r\n"
				+ "                                    \"PageNumber\": 1,\r\n"
				+ "                                    \"TextAlign\": \"Left\",\r\n"
				+ "                                    \"Position\": {\r\n"
				+ "                                        \"PositionX\": 396.0,\r\n"
				+ "                                        \"PositionY\": 83.0\r\n"
				+ "                                    },\r\n"
				+ "                                    \"DefaultText\": \"##ReceiverFirstName## ##ReceiverLastName##\",\r\n"
				+ "                                    \"TextFormat\": \"\",\r\n"
				+ "                                    \"DefaultTextType\": \"FullName\",\r\n"
				+ "                                    \"FontSettings\": {\r\n"
				+ "                                        \"Id\": \"54bd6c45-9ebc-460e-a819-9c4f6132c833\",\r\n"
				+ "                                        \"TextColor\": {\r\n"
				+ "                                            \"A\": 255,\r\n"
				+ "                                            \"R\": 0,\r\n"
				+ "                                            \"G\": 0,\r\n"
				+ "                                            \"B\": 0\r\n"
				+ "                                        },\r\n"
				+ "                                        \"Name\": \"Times New Roman\",\r\n"
				+ "                                        \"Size\": 11.0,\r\n"
				+ "                                        \"IsBold\": false,\r\n"
				+ "                                        \"IsItalic\": false\r\n"
				+ "                                    },\r\n"
				+ "                                    \"IsEditablePosition\": false,\r\n"
				+ "                                    \"IsEditableDefaultText\": false,\r\n"
				+ "                                    \"IsEditableFontSettings\": false,\r\n"
				+ "                                    \"IsRequired\": false,\r\n"
				+ "                                    \"Id\": \"a1959a38-d6f2-4e6a-b8d9-26f123fd2811\",\r\n"
				+ "                                    \"DocRefNumber\": 1,\r\n"
				+ "                                    \"DiscriminatorType\": \"TypewriterAnnotation\"\r\n"
				+ "                                },\r\n"
				+ "                                {\r\n"
				+ "                                    \"PageNumber\": 1,\r\n"
				+ "                                    \"TextAlign\": \"Left\",\r\n"
				+ "                                    \"Position\": {\r\n"
				+ "                                        \"PositionX\": 396.0,\r\n"
				+ "                                        \"PositionY\": 67.0\r\n"
				+ "                                    },\r\n"
				+ "                                    \"DefaultText\": \"##ClientTime##\",\r\n"
				+ "                                    \"TextFormat\": \"dd/MM/yyyy\",\r\n"
				+ "                                    \"DefaultTextType\": \"DateTime\",\r\n"
				+ "                                    \"FontSettings\": {\r\n"
				+ "                                        \"Id\": \"54bd6c45-9ebc-460e-a819-9c4f6132c833\",\r\n"
				+ "                                        \"TextColor\": {\r\n"
				+ "                                            \"A\": 255,\r\n"
				+ "                                            \"R\": 0,\r\n"
				+ "                                            \"G\": 0,\r\n"
				+ "                                            \"B\": 0\r\n"
				+ "                                        },\r\n"
				+ "                                        \"Name\": \"Times New Roman\",\r\n"
				+ "                                        \"Size\": 11.0,\r\n"
				+ "                                        \"IsBold\": false,\r\n"
				+ "                                        \"IsItalic\": false\r\n"
				+ "                                    },\r\n"
				+ "                                    \"IsEditablePosition\": false,\r\n"
				+ "                                    \"IsEditableDefaultText\": false,\r\n"
				+ "                                    \"IsEditableFontSettings\": false,\r\n"
				+ "                                    \"IsRequired\": false,\r\n"
				+ "                                    \"Id\": \"4aa956d2-9d40-40a0-8536-af01acfb6a96\",\r\n"
				+ "                                    \"DocRefNumber\": 1,\r\n"
				+ "                                    \"DiscriminatorType\": \"TypewriterAnnotation\"\r\n"
				+ "                                },\r\n"
				+ "                                {\r\n"
				+ "                                    \"PositionPage\": 1,\r\n"
				+ "                                    \"Position\": {\r\n"
				+ "                                        \"PositionX\": 323,\r\n"
				+ "                                        \"PositionY\": 131.92\r\n"
				+ "                                    },\r\n"
				+ "                                    \"Size\": {\r\n"
				+ "                                        \"Height\": 80.0,\r\n"
				+ "                                        \"Width\": 190.0\r\n"
				+ "                                    },\r\n"
				+ "                                    \"AdditionalParameters\": [\r\n"
				+ "                                        {\r\n"
				+ "                                            \"Key\": \"enabled\",\r\n"
				+ "                                            \"Value\": \"1\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"Key\": \"positioning\",\r\n"
				+ "                                            \"Value\": \"onPage\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"Key\": \"req\",\r\n"
				+ "                                            \"Value\": \"1\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"Key\": \"fd\",\r\n"
				+ "                                            \"Value\": \"\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"Key\": \"fd_dateformat\",\r\n"
				+ "                                            \"Value\": \"dd-MM-yyyy HH:mm:ss\"\r\n"
				+ "                                        },\r\n"
				+ "                                        {\r\n"
				+ "                                            \"Key\": \"fd_timezone\",\r\n"
				+ "                                            \"Value\": \"datetimeutc\"\r\n"
				+ "                                        }\r\n"
				+ "                                    ],\r\n"
				+ "                                    \"AllowedSignatureTypes\": [\r\n"
				+ "                                        {\r\n"
				+ "                                            \"AllowedCapturingMethod\": \"Click2Sign\",\r\n"
				+ "                                            \"Id\": \"02b8cd6f-1624-4532-b110-3c9e7a79cd4e\",\r\n"
				+ "                                            \"DiscriminatorType\": \"SigTypeClick2Sign\",\r\n"
				+ "                                            \"Preferred\": false,\r\n"
				+ "                                            \"StampImprintConfiguration\": {\r\n"
				+ "                                                \"DisplayExtraInformation\": true,\r\n"
				+ "                                                \"DisplayEmail\": true,\r\n"
				+ "                                                \"DisplayIp\": true,\r\n"
				+ "                                                \"DisplayName\": true,\r\n"
				+ "                                                \"DisplaySignatureDate\": true,\r\n"
				+ "                                                \"FontFamily\": \"Times New Roman\",\r\n"
				+ "                                                \"FontSize\": 11.0\r\n"
				+ "                                            }\r\n"
				+ "                                        }\r\n"
				+ "                                    ],\r\n"
				+ "                                    \"UseTimestamp\": false,\r\n"
				+ "                                    \"IsRequired\": true,\r\n"
				+ "                                    \"Id\": \"1#XyzmoDuplicateIdSeperator#Signature_1315bf9f-1a2b-d92f-2d3a-1829314e2d20\",\r\n"
				+ "                                    \"DisplayName\": \"\",\r\n"
				+ "                                    \"DocRefNumber\": 1,\r\n"
				+ "                                    \"DiscriminatorType\": \"Signature\"\r\n"
				+ "                                }\r\n"
				+ "                            ]\r\n"
				+ "                        }\r\n"
				+ "                    },\r\n"
				+ "                    \"Navigation\": {\r\n"
				+ "                        \"HyperLinks\": [],\r\n"
				+ "                        \"Links\": [],\r\n"
				+ "                        \"LinkTargets\": []\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                \"DocumentOptions\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"DocumentReference\": \"1\",\r\n"
				+ "                        \"IsHidden\": false\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"UseDefaultAgreements\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"OrderIndex\": 3,\r\n"
				+ "                \"Recipients\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"Email\": \""+r1Email+"\",\r\n"
				+ "                        \"FirstName\": \""+r1FirstName+"\",\r\n"
				+ "                        \"LastName\": \""+r1LastName+"\",\r\n"
				+ "                        \"LanguageCode\": \"en\",\r\n"
				+ "                        \"EmailBodyExtra\": \"\",\r\n"
				+ "                        \"DisableEmail\": false,\r\n"
				+ "                        \"AddAndroidAppLink\": false,\r\n"
				+ "                        \"AddIosAppLink\": false,\r\n"
				+ "                        \"AddWindowsAppLink\": false,\r\n"
				+ "                        \"AllowDelegation\": false,\r\n"
				+ "                        \"SkipExternalDataValidation\": false,\r\n"
				+ "                        \"AuthenticationMethods\": []\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"EmailBodyExtra\": \"\",\r\n"
				+ "                \"RecipientType\": \"Cc\",\r\n"
				+ "                \"DocumentOptions\": [],\r\n"
				+ "                \"UseDefaultAgreements\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"OrderIndex\": 4,\r\n"
				+ "                \"Recipients\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"Email\": \""+r2Email+"\",\r\n"
				+ "                        \"FirstName\": \""+r2FirstName+"\",\r\n"
				+ "                        \"LastName\": \""+r2LastName+"\",\r\n"
				+ "                        \"LanguageCode\": \"en\",\r\n"
				+ "                        \"EmailBodyExtra\": \"\",\r\n"
				+ "                        \"DisableEmail\": false,\r\n"
				+ "                        \"AddAndroidAppLink\": false,\r\n"
				+ "                        \"AddIosAppLink\": false,\r\n"
				+ "                        \"AddWindowsAppLink\": false,\r\n"
				+ "                        \"AllowDelegation\": false,\r\n"
				+ "                        \"SkipExternalDataValidation\": false,\r\n"
				+ "                        \"AuthenticationMethods\": []\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"EmailBodyExtra\": \"\",\r\n"
				+ "                \"RecipientType\": \"Cc\",\r\n"
				+ "                \"DocumentOptions\": [],\r\n"
				+ "                \"UseDefaultAgreements\": false\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"AddFormFields\": {\r\n"
				+ "            \"Forms\": {\r\n"
				+ "                \"1\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"Value\": \"\",\r\n"
				+ "                        \"MaxLength\": -1,\r\n"
				+ "                        \"IsMultiline\": false,\r\n"
				+ "                        \"IsPassword\": false,\r\n"
				+ "                        \"IsComb\": false,\r\n"
				+ "                        \"TextColor\": \"0, 0, 0\",\r\n"
				+ "                        \"FontSize\": 11.0,\r\n"
				+ "                        \"FontName\": \"Times New Roman\",\r\n"
				+ "                        \"Bold\": false,\r\n"
				+ "                        \"Italic\": false,\r\n"
				+ "                        \"TextAlign\": \"Left\",\r\n"
				+ "                        \"Name\": \"TextBox_CustomerName\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 162.0,\r\n"
				+ "                        \"Y\": 676.92,\r\n"
				+ "                        \"Width\": 358.0,\r\n"
				+ "                        \"Height\": 20.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddTextBoxFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"Value\": \"\",\r\n"
				+ "                        \"MaxLength\": -1,\r\n"
				+ "                        \"IsMultiline\": false,\r\n"
				+ "                        \"IsPassword\": false,\r\n"
				+ "                        \"IsComb\": false,\r\n"
				+ "                        \"TextColor\": \"0, 0, 0\",\r\n"
				+ "                        \"FontSize\": 11.0,\r\n"
				+ "                        \"FontName\": \"Times New Roman\",\r\n"
				+ "                        \"Bold\": false,\r\n"
				+ "                        \"Italic\": false,\r\n"
				+ "                        \"TextAlign\": \"Left\",\r\n"
				+ "                        \"Name\": \"TextBox_CustomerAddress\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 163.0,\r\n"
				+ "                        \"Y\": 653.92,\r\n"
				+ "                        \"Width\": 358.0,\r\n"
				+ "                        \"Height\": 20.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddTextBoxFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"Value\": \"\",\r\n"
				+ "                        \"MaxLength\": -1,\r\n"
				+ "                        \"IsMultiline\": false,\r\n"
				+ "                        \"IsPassword\": false,\r\n"
				+ "                        \"IsComb\": false,\r\n"
				+ "                        \"TextColor\": \"0, 0, 0\",\r\n"
				+ "                        \"FontSize\": 11.0,\r\n"
				+ "                        \"FontName\": \"Times New Roman\",\r\n"
				+ "                        \"Bold\": false,\r\n"
				+ "                        \"Italic\": false,\r\n"
				+ "                        \"TextAlign\": \"Left\",\r\n"
				+ "                        \"Name\": \"TextBox_CustomerMobile\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 140.0,\r\n"
				+ "                        \"Y\": 631.92,\r\n"
				+ "                        \"Width\": 382.0,\r\n"
				+ "                        \"Height\": 20.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddTextBoxFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"Value\": \"\",\r\n"
				+ "                        \"MaxLength\": -1,\r\n"
				+ "                        \"IsMultiline\": false,\r\n"
				+ "                        \"IsPassword\": false,\r\n"
				+ "                        \"IsComb\": false,\r\n"
				+ "                        \"TextColor\": \"0, 0, 0\",\r\n"
				+ "                        \"FontSize\": 11.0,\r\n"
				+ "                        \"FontName\": \"Times New Roman\",\r\n"
				+ "                        \"Bold\": false,\r\n"
				+ "                        \"Italic\": false,\r\n"
				+ "                        \"TextAlign\": \"Left\",\r\n"
				+ "                        \"Name\": \"TextBox_CustomerEmail\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 109.0,\r\n"
				+ "                        \"Y\": 607.92,\r\n"
				+ "                        \"Width\": 412.0,\r\n"
				+ "                        \"Height\": 20.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddTextBoxFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"ExportValue\": \"USB64GB\",\r\n"
				+ "                        \"IsChecked\": false,\r\n"
				+ "                        \"Name\": \"RadioButton_USB64GB\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 266.0,\r\n"
				+ "                        \"Y\": 533.92,\r\n"
				+ "                        \"Width\": 20.0,\r\n"
				+ "                        \"Height\": 20.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddRadioButtonFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"Value\": \"0\",\r\n"
				+ "                        \"Items\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"0\",\r\n"
				+ "                                \"DisplayValue\": \"0 USB\",\r\n"
				+ "                                \"IsSelected\": true\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"1\",\r\n"
				+ "                                \"DisplayValue\": \"1 USB\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"2\",\r\n"
				+ "                                \"DisplayValue\": \"2 USB\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"3\",\r\n"
				+ "                                \"DisplayValue\": \"3 USB\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            }\r\n"
				+ "                        ],\r\n"
				+ "                        \"TextColor\": \"\",\r\n"
				+ "                        \"FontSize\": 11.0,\r\n"
				+ "                        \"FontName\": \"Times New Roman\",\r\n"
				+ "                        \"Bold\": false,\r\n"
				+ "                        \"Italic\": false,\r\n"
				+ "                        \"TextAlign\": \"Left\",\r\n"
				+ "                        \"Name\": \"ComboBox_USB64GB\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 355.0,\r\n"
				+ "                        \"Y\": 530.92,\r\n"
				+ "                        \"Width\": 113.0,\r\n"
				+ "                        \"Height\": 26.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddComboBoxFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"ExportValue\": \"USB128GB\",\r\n"
				+ "                        \"IsChecked\": false,\r\n"
				+ "                        \"Name\": \"RadioButton_USB128GB\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 265.0,\r\n"
				+ "                        \"Y\": 505.92,\r\n"
				+ "                        \"Width\": 20.0,\r\n"
				+ "                        \"Height\": 20.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddRadioButtonFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"Value\": \"0\",\r\n"
				+ "                        \"Items\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"0\",\r\n"
				+ "                                \"DisplayValue\": \"0 USB\",\r\n"
				+ "                                \"IsSelected\": true\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"1\",\r\n"
				+ "                                \"DisplayValue\": \"1 USB\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"2\",\r\n"
				+ "                                \"DisplayValue\": \"2 USB\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"3\",\r\n"
				+ "                                \"DisplayValue\": \"3 USB\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            }\r\n"
				+ "                        ],\r\n"
				+ "                        \"TextColor\": \"\",\r\n"
				+ "                        \"FontSize\": 11.0,\r\n"
				+ "                        \"FontName\": \"Times New Roman\",\r\n"
				+ "                        \"Bold\": false,\r\n"
				+ "                        \"Italic\": false,\r\n"
				+ "                        \"TextAlign\": \"Left\",\r\n"
				+ "                        \"Name\": \"ComboBox_USB128GB\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 356.0,\r\n"
				+ "                        \"Y\": 505.92,\r\n"
				+ "                        \"Width\": 112.0,\r\n"
				+ "                        \"Height\": 22.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddComboBoxFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"ExportValue\": \"SSD512GB\",\r\n"
				+ "                        \"IsChecked\": false,\r\n"
				+ "                        \"Name\": \"RadioButton_SSD512GB\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 265.0,\r\n"
				+ "                        \"Y\": 478.92,\r\n"
				+ "                        \"Width\": 20.0,\r\n"
				+ "                        \"Height\": 20.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddRadioButtonFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"Value\": \"0\",\r\n"
				+ "                        \"Items\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"0\",\r\n"
				+ "                                \"DisplayValue\": \"0 SSD\",\r\n"
				+ "                                \"IsSelected\": true\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"1\",\r\n"
				+ "                                \"DisplayValue\": \"1 SSD\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"2\",\r\n"
				+ "                                \"DisplayValue\": \"2 SSD\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"3\",\r\n"
				+ "                                \"DisplayValue\": \"3 SSD\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            }\r\n"
				+ "                        ],\r\n"
				+ "                        \"TextColor\": \"\",\r\n"
				+ "                        \"FontSize\": 11.0,\r\n"
				+ "                        \"FontName\": \"Times New Roman\",\r\n"
				+ "                        \"Bold\": false,\r\n"
				+ "                        \"Italic\": false,\r\n"
				+ "                        \"TextAlign\": \"Left\",\r\n"
				+ "                        \"Name\": \"ComboBox_SSD512GB\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 356.0,\r\n"
				+ "                        \"Y\": 476.92,\r\n"
				+ "                        \"Width\": 110.0,\r\n"
				+ "                        \"Height\": 25.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddComboBoxFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"ExportValue\": \"SSD1TB\",\r\n"
				+ "                        \"IsChecked\": false,\r\n"
				+ "                        \"Name\": \"RadioButton_SSD1TB\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 265.0,\r\n"
				+ "                        \"Y\": 452.92,\r\n"
				+ "                        \"Width\": 20.0,\r\n"
				+ "                        \"Height\": 20.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddRadioButtonFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"Value\": \"0\",\r\n"
				+ "                        \"Items\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"0\",\r\n"
				+ "                                \"DisplayValue\": \"0 SSD\",\r\n"
				+ "                                \"IsSelected\": true\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"1\",\r\n"
				+ "                                \"DisplayValue\": \"1 SSD\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"2\",\r\n"
				+ "                                \"DisplayValue\": \"2 SSD\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"3\",\r\n"
				+ "                                \"DisplayValue\": \"3 SSD\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            }\r\n"
				+ "                        ],\r\n"
				+ "                        \"TextColor\": \"\",\r\n"
				+ "                        \"FontSize\": 11.0,\r\n"
				+ "                        \"FontName\": \"Times New Roman\",\r\n"
				+ "                        \"Bold\": false,\r\n"
				+ "                        \"Italic\": false,\r\n"
				+ "                        \"TextAlign\": \"Left\",\r\n"
				+ "                        \"Name\": \"ComboBox_SSD1TB\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 355.0,\r\n"
				+ "                        \"Y\": 447.92,\r\n"
				+ "                        \"Width\": 112.0,\r\n"
				+ "                        \"Height\": 26.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddComboBoxFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"ExportValue\": \"HDD512GB\",\r\n"
				+ "                        \"IsChecked\": false,\r\n"
				+ "                        \"Name\": \"RadioButton_HDD512GB\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 265.0,\r\n"
				+ "                        \"Y\": 422.92,\r\n"
				+ "                        \"Width\": 20.0,\r\n"
				+ "                        \"Height\": 20.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddRadioButtonFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"Value\": \"0\",\r\n"
				+ "                        \"Items\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"0\",\r\n"
				+ "                                \"DisplayValue\": \"0 HDD\",\r\n"
				+ "                                \"IsSelected\": true\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"1\",\r\n"
				+ "                                \"DisplayValue\": \"1 HDD\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"2\",\r\n"
				+ "                                \"DisplayValue\": \"2 HDD\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"3\",\r\n"
				+ "                                \"DisplayValue\": \"3 HDD\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            }\r\n"
				+ "                        ],\r\n"
				+ "                        \"TextColor\": \"\",\r\n"
				+ "                        \"FontSize\": 11.0,\r\n"
				+ "                        \"FontName\": \"Times New Roman\",\r\n"
				+ "                        \"Bold\": false,\r\n"
				+ "                        \"Italic\": false,\r\n"
				+ "                        \"TextAlign\": \"Left\",\r\n"
				+ "                        \"Name\": \"ComboBox_HDD512GB\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 356.0,\r\n"
				+ "                        \"Y\": 420.92,\r\n"
				+ "                        \"Width\": 111.0,\r\n"
				+ "                        \"Height\": 24.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddComboBoxFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"ExportValue\": \"HDD1TB\",\r\n"
				+ "                        \"IsChecked\": false,\r\n"
				+ "                        \"Name\": \"RadioButton_HDD1TB\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 264.0,\r\n"
				+ "                        \"Y\": 393.92,\r\n"
				+ "                        \"Width\": 20.0,\r\n"
				+ "                        \"Height\": 20.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddRadioButtonFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"Value\": \"0\",\r\n"
				+ "                        \"Items\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"0\",\r\n"
				+ "                                \"DisplayValue\": \"0 HDD\",\r\n"
				+ "                                \"IsSelected\": true\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"1\",\r\n"
				+ "                                \"DisplayValue\": \"1 HDD\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"2\",\r\n"
				+ "                                \"DisplayValue\": \"2 HDD\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"ExportValue\": \"3\",\r\n"
				+ "                                \"DisplayValue\": \"3 HDD\",\r\n"
				+ "                                \"IsSelected\": false\r\n"
				+ "                            }\r\n"
				+ "                        ],\r\n"
				+ "                        \"TextColor\": \"\",\r\n"
				+ "                        \"FontSize\": 11.0,\r\n"
				+ "                        \"FontName\": \"Times New Roman\",\r\n"
				+ "                        \"Bold\": false,\r\n"
				+ "                        \"Italic\": false,\r\n"
				+ "                        \"TextAlign\": \"Left\",\r\n"
				+ "                        \"Name\": \"ComboBox_HDD1TB\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 356.0,\r\n"
				+ "                        \"Y\": 391.92,\r\n"
				+ "                        \"Width\": 109.0,\r\n"
				+ "                        \"Height\": 26.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddComboBoxFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"IsChecked\": false,\r\n"
				+ "                        \"Name\": \"CheckBox_b3051d21-84b4-6d3f-04bf-628688694419\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": true,\r\n"
				+ "                        \"X\": 72.0,\r\n"
				+ "                        \"Y\": 349.91999999999996,\r\n"
				+ "                        \"Width\": 20.0,\r\n"
				+ "                        \"Height\": 20.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddCheckBoxFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"IsChecked\": false,\r\n"
				+ "                        \"Name\": \"CheckBox_198c738c-6388-ddc4-f119-f9bfe63716c9\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": true,\r\n"
				+ "                        \"X\": 72.0,\r\n"
				+ "                        \"Y\": 326.91999999999996,\r\n"
				+ "                        \"Width\": 20.0,\r\n"
				+ "                        \"Height\": 20.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddCheckBoxFormFieldDescriptor\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"IsChecked\": false,\r\n"
				+ "                        \"Name\": \"CheckBox_2ce4c1c0-1a65-cdf5-6a26-b73063c3ffd5\",\r\n"
				+ "                        \"ReadOnly\": false,\r\n"
				+ "                        \"Required\": false,\r\n"
				+ "                        \"X\": 72.0,\r\n"
				+ "                        \"Y\": 303.91999999999996,\r\n"
				+ "                        \"Width\": 20.0,\r\n"
				+ "                        \"Height\": 20.0,\r\n"
				+ "                        \"Page\": 1,\r\n"
				+ "                        \"DiscriminatorType\": \"AddCheckBoxFormFieldDescriptor\"\r\n"
				+ "                    }\r\n"
				+ "                ]\r\n"
				+ "            }\r\n"
				+ "        },\r\n"
				+ "        \"OverrideFormFieldValues\": {\r\n"
				+ "            \"Forms\": {}\r\n"
				+ "        },\r\n"
				+ "        \"AttachSignedDocumentsToEnvelopeLog\": false\r\n"
				+ "    }\r\n"
				+ "}";
	}

}
