package com.Contum.Integration.models;

public class orderLongTerm extends sendEnvelopeBase{
	public static String userId;
	public static String deviceID;
	
	public static String getUserId() {
		return userId;
	}



	public static void setUserId(String userId) {
		orderLongTerm.userId = userId;
	}



	public static String getDeviceID() {
		return deviceID;
	}



	public static void setDeviceID(String deviceID) {
		orderLongTerm.deviceID = deviceID;
	}



	public static void setParameters(String envelopeName, String r1Email, String r1FirstName, String r1LastName,String r2Email, String r2FirstName, String r2LastName ,String userId, String deviceID) {
		setEnvelopeName(envelopeName);
		setR1Email(r1Email);
		setR1FirstName(r1FirstName);
		setR1LastName(r1LastName);
		setUserId(userId);
		setDeviceID(deviceID);
		setR2Email(r2Email);
		setR2FirstName(r2FirstName);
		setR2LastName(r2LastName);
	}
		


	public static String getRequest() {
		return "{\r\n"
				+ "    \"SspFileIds\": [\r\n"
				+ "       \" "+sspFileId+"\"\r\n"
				+ "    ],\r\n"
				+ "    \"SendEnvelopeDescription\": {\r\n"
				+ "        \r\n"
				+ "            \"Name\": \""+envelopeName+"\",\r\n"
				+ "            \"EmailSubject\": \"Please sign the enclosed envelope\",\r\n"
				+ "            \"EmailBody\": \"Dear #RecipientFirstName# #RecipientLastName#\\n\\n#PersonalMessage#\\n\\nPlease sign the envelope #EnvelopeName#\\n\\nEnvelope will expire at #ExpirationDate#\",\r\n"
				+ "            \"DisplayedEmailSender\": \"\",\r\n"
				+ "            \"EnableReminders\": true,\r\n"
				+ "            \"FirstReminderDayAmount\": 5,\r\n"
				+ "            \"RecurrentReminderDayAmount\": 3,\r\n"
				+ "            \"BeforeExpirationDayAmount\": 3,\r\n"
				+ "            \"ExpirationInSecondsAfterSending\": 2419200,\r\n"
				+ "            \"CallbackUrl\": \"\",\r\n"
				+ "            \"StatusUpdateCallbackUrl\": \"\",\r\n"
				+ "            \"LockFormFieldsAtEnvelopeFinish\": false,\r\n"
				+ "            \"Steps\": [\r\n"
				+ "                {\r\n"
				+ "                    \"OrderIndex\": 1,\r\n"
				+ "                    \"Recipients\": [\r\n"
				+ "                        {\r\n"
				+ "                            \"Email\": \""+r1Email+"\",\r\n"
				+ "                            \"FirstName\": \""+r1FirstName+"\",\r\n"
				+ "                            \"LastName\": \""+r1LastName+"\",\r\n"
				+ "                            \"LanguageCode\": \"en\",\r\n"
				+ "                            \"EmailBodyExtra\": \"\",\r\n"
				+ "                            \"DisableEmail\": false,\r\n"
				+ "                            \"AddAndroidAppLink\": false,\r\n"
				+ "                            \"AddIosAppLink\": false,\r\n"
				+ "                            \"AddWindowsAppLink\": false,\r\n"
				+ "                            \"AllowDelegation\": true,\r\n"
				+ "                            \"AllowAccessFinishedWorkstep\": false,\r\n"
				+ "                            \"SkipExternalDataValidation\": false,\r\n"
				+ "                            \"AuthenticationMethods\": [],\r\n"
				+ "                            \"DisposableCertificateData\": {\r\n"
				+ "                                \"CountryResidence\": \"HU\",\r\n"
				+ "                                \"DocumentIssuingCountry\": \"\",\r\n"
				+ "                                \"IdentificationCountry\": \"HU\",\r\n"
				+ "                                \"IdentificationType\": \"PASSPORT\",\r\n"
				+ "                                \"PhoneMobile\": \"+36703881503\",\r\n"
				+ "                                \"DocumentType\": \"PASS\",\r\n"
				+ "                                \"DocumentIssuedBy\": \"KEK\",\r\n"
				+ "                                \"DocumentIssuedOn\": \"2021-06-01T00:00:00Z\",\r\n"
				+ "                                \"DocumentExpiryDate\": \"2021-10-13T00:00:00Z\",\r\n"
				+ "                                \"SerialNumber\": \"12345\",\r\n"
				+ "                                \"DocumentNumber\": \"1234\",\r\n"
				+ "                                \"OverrideHolderInCaseOfMismatch\": false\r\n"
				+ "                            }\r\n"
				+ "                        }\r\n"
				+ "                    ],\r\n"
				+ "                    \"EmailBodyExtra\": \"\",\r\n"
				+ "                    \"RecipientType\": \"Signer\",\r\n"
				+ "                    \"WorkstepConfiguration\": {\r\n"
				+ "                        \"WorkstepLabel\": \"szerzodes\",\r\n"
				+ "                        \"SmallTextZoomFactorPercent\": 100,\r\n"
				+ "                        \"FinishAction\": {\r\n"
				+ "                            \"ServerActions\": [],\r\n"
				+ "                            \"ClientActions\": []\r\n"
				+ "                        },\r\n"
				+ "                        \"ReceiverInformation\": {\r\n"
				+ "                            \"UserInformation\": {\r\n"
				+ "                                \"FirstName\": \""+r1FirstName+"\",\r\n"
				+ "                                \"LastName\": \""+r1LastName+"\",\r\n"
				+ "                                \"EMail\": \""+r1Email+"\"\r\n"
				+ "                            },\r\n"
				+ "                            \"HolderInformation\": \"<recognitionType>PASS</recognitionType><documentIssuedOn>01/06/2021</documentIssuedOn><documentExpiryDate>13/10/2021</documentExpiryDate><documentIssuedBy>KEK</documentIssuedBy><documentNumber>1234</documentNumber><countryResidence>HU</countryResidence><firstName>Bence Gábor</firstName><lastName>Katona</lastName><email>gabor.katona@contum.hu</email><phoneMobile>+36703881503</phoneMobile><identificationType>PASSPORT</identificationType><identificationCountry>HU</identificationCountry><passport>12345</passport>\",\r\n"
				+ "                            \"TransactionCodePushPluginData\": []\r\n"
				+ "                        },\r\n"
				+ "                        \"SenderInformation\": {\r\n"
				+ "                            \"UserInformation\": {\r\n"
				+ "                                \"FirstName\":\""+r2FirstName+"\",\r\n"
				+ "                                \"LastName\": \""+r2LastName+"\",\r\n"
				+ "                                \"EMail\": \""+r2Email+"\"\r\n"
				+ "                            }\r\n"
				+ "                        },\r\n"
				+ "                        \"TransactionCodeConfigurations\": [],\r\n"
				+ "                        \"SignatureConfigurations\": [],\r\n"
				+ "                        \"ViewerPreferences\": {\r\n"
				+ "                            \"FinishWorkstepOnOpen\": false,\r\n"
				+ "                            \"VisibleAreaOptions\": {\r\n"
				+ "                                \"AllowedDomain\": \"*\",\r\n"
				+ "                                \"Enabled\": false\r\n"
				+ "                            }\r\n"
				+ "                        },\r\n"
				+ "                        \"ResourceUris\": {\r\n"
				+ "                            \"DelegationUri\": \"https://demo.esignanywhere.net/Resource/Delegate\"\r\n"
				+ "                        },\r\n"
				+ "                        \"AdditionalClientWorkstepInformation\": \"<metaData />\",\r\n"
				+ "                        \"AuditingToolsConfiguration\": {\r\n"
				+ "                            \"WriteAuditTrail\": true,\r\n"
				+ "                            \"NotificationConfiguration\": {}\r\n"
				+ "                        },\r\n"
				+ "                        \"Policy\": {\r\n"
				+ "                            \"GeneralPolicies\": {\r\n"
				+ "                                \"AllowSaveDocument\": true,\r\n"
				+ "                                \"AllowSaveAuditTrail\": true,\r\n"
				+ "                                \"AllowRotatingPages\": false,\r\n"
				+ "                                \"AllowEmailDocument\": true,\r\n"
				+ "                                \"AllowPrintDocument\": true,\r\n"
				+ "                                \"AllowFinishWorkstep\": true,\r\n"
				+ "                                \"AllowRejectWorkstep\": true,\r\n"
				+ "                                \"AllowRejectWorkstepDelegation\": true,\r\n"
				+ "                                \"AllowUndoLastAction\": false,\r\n"
				+ "                                \"AllowAdhocPdfAttachments\": false,\r\n"
				+ "                                \"AllowAdhocSignatures\": false,\r\n"
				+ "                                \"AllowAdhocStampings\": false,\r\n"
				+ "                                \"AllowAdhocFreeHandAnnotations\": false,\r\n"
				+ "                                \"AllowAdhocTypewriterAnnotations\": false,\r\n"
				+ "                                \"AllowAdhocPictureAnnotations\": false,\r\n"
				+ "                                \"AllowAdhocPdfPageAppending\": false\r\n"
				+ "                            },\r\n"
				+ "                            \"WorkstepTasks\": {\r\n"
				+ "                                \"PictureAnnotationMinResolution\": 0,\r\n"
				+ "                                \"PictureAnnotationMaxResolution\": 0,\r\n"
				+ "                                \"PictureAnnotationColorDepth\": \"Color16M\",\r\n"
				+ "                                \"SequenceMode\": \"NoSequenceEnforced\",\r\n"
				+ "                                \"PositionUnits\": \"PdfUnits\",\r\n"
				+ "                                \"ReferenceCorner\": \"Lower_Left\",\r\n"
				+ "                                \"Tasks\": [\r\n"
				+ "                                    {\r\n"
				+ "                                        \"PositionPage\": 2,\r\n"
				+ "                                        \"Position\": {\r\n"
				+ "                                            \"PositionX\": 91.0,\r\n"
				+ "                                            \"PositionY\": 684.92\r\n"
				+ "                                        },\r\n"
				+ "                                        \"Size\": {\r\n"
				+ "                                            \"Height\": 71.0,\r\n"
				+ "                                            \"Width\": 190.0\r\n"
				+ "                                        },\r\n"
				+ "                                        \"AdditionalParameters\": [\r\n"
				+ "                                            {\r\n"
				+ "                                                \"Key\": \"enabled\",\r\n"
				+ "                                                \"Value\": \"1\"\r\n"
				+ "                                            },\r\n"
				+ "                                            {\r\n"
				+ "                                                \"Key\": \"positioning\",\r\n"
				+ "                                                \"Value\": \"onPage\"\r\n"
				+ "                                            },\r\n"
				+ "                                            {\r\n"
				+ "                                                \"Key\": \"req\",\r\n"
				+ "                                                \"Value\": \"1\"\r\n"
				+ "                                            },\r\n"
				+ "                                            {\r\n"
				+ "                                                \"Key\": \"fd\",\r\n"
				+ "                                                \"Value\": \"\"\r\n"
				+ "                                            },\r\n"
				+ "                                            {\r\n"
				+ "                                                \"Key\": \"fd_dateformat\",\r\n"
				+ "                                                \"Value\": \"dd-MM-yyyy HH:mm:ss\"\r\n"
				+ "                                            },\r\n"
				+ "                                            {\r\n"
				+ "                                                \"Key\": \"fd_timezone\",\r\n"
				+ "                                                \"Value\": \"datetimeutc\"\r\n"
				+ "                                            },\r\n"
				+ "                                            {\r\n"
				+ "                                                \"Key\": \"spcId\",\r\n"
				+ "                                                \"Value\": \"ltaLevelId\"\r\n"
				+ "                                            }\r\n"
				+ "                                        ],\r\n"
				+ "                                        \"AllowedSignatureTypes\": [\r\n"
				+ "                                            {\r\n"
				+ "                                                \"TrModType\": \"RemoteSignatureDisposableCertificate\",\r\n"
				+ "                                                \"TrValidityInSeconds\": 300,\r\n"
				+ "                                                \"TrConfIdIssueCertificate\": \"disposableCertificateEnrolAndSignSmsText\",\r\n"
				+ "                                                \"TrConfId\": \"remoteCertificateSignSmsText\",\r\n"
				+ "                                                \"IsPhoneNumberRequired\": false,\r\n"
				+ "                                                \"Ly\": \"remoteCertificate\",\r\n"
				+ "                                                \"Id\": \"80d07024-24f1-42d3-8a59-f255584f3a9c\",\r\n"
				+ "                                                \"DiscriminatorType\": \"SigTypeTransactionCode\",\r\n"
				+ "                                                \"Preferred\": false,\r\n"
				+ "                                                \"StampImprintConfiguration\": {\r\n"
				+ "                                                    \"DisplayExtraInformation\": true,\r\n"
				+ "                                                    \"DisplayEmail\": true,\r\n"
				+ "                                                    \"DisplayIp\": true,\r\n"
				+ "                                                    \"DisplayName\": true,\r\n"
				+ "                                                    \"DisplaySignatureDate\": true,\r\n"
				+ "                                                    \"FontFamily\": \"Times New Roman\",\r\n"
				+ "                                                    \"FontSize\": 11.0\r\n"
				+ "                                                }\r\n"
				+ "                                            }\r\n"
				+ "                                        ],\r\n"
				+ "                                        \"UseTimestamp\": false,\r\n"
				+ "                                        \"IsRequired\": true,\r\n"
				+ "                                        \"Id\": \"1#XyzmoDuplicateIdSeperator#Signature_42a2e1f7-141f-925e-bc1f-6a23ce16e42c\",\r\n"
				+ "                                        \"DisplayName\": \"\",\r\n"
				+ "                                        \"DocRefNumber\": 1,\r\n"
				+ "                                        \"DiscriminatorType\": \"Signature\"\r\n"
				+ "                                    }\r\n"
				+ "                                ]\r\n"
				+ "                            },\r\n"
				+ "                            \"FinalizeActions\": {\r\n"
				+ "                                \"FinalizeActionList\": [\r\n"
				+ "                                    {\r\n"
				+ "                                        \"DocRefNumbers\": \"*\",\r\n"
				+ "                                        \"SpcId\": \"ltaLevelId\",\r\n"
				+ "                                        \"DiscriminatorType\": \"Timestamp\"\r\n"
				+ "                                    }\r\n"
				+ "                                ]\r\n"
				+ "                            }\r\n"
				+ "                        },\r\n"
				+ "                        \"Navigation\": {\r\n"
				+ "                            \"HyperLinks\": [],\r\n"
				+ "                            \"Links\": [],\r\n"
				+ "                            \"LinkTargets\": []\r\n"
				+ "                        }\r\n"
				+ "                    },\r\n"
				+ "                    \"DocumentOptions\": [\r\n"
				+ "                        {\r\n"
				+ "                            \"DocumentReference\": \"1\",\r\n"
				+ "                            \"IsHidden\": false\r\n"
				+ "                        }\r\n"
				+ "                    ],\r\n"
				+ "                    \"UseDefaultAgreements\": true\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"OrderIndex\": 2,\r\n"
				+ "                    \"Recipients\": [\r\n"
				+ "                        {\r\n"
				+ "                            \"Email\": \""+r2Email+"\",\r\n"
				+ "                            \"FirstName\": \""+r2FirstName+"\",\r\n"
				+ "                            \"LastName\": \""+r2LastName+"\",\r\n"
				+ "                            \"LanguageCode\": \"en\",\r\n"
				+ "                            \"EmailBodyExtra\": \"\",\r\n"
				+ "                            \"DisableEmail\": false,\r\n"
				+ "                            \"AddAndroidAppLink\": false,\r\n"
				+ "                            \"AddIosAppLink\": false,\r\n"
				+ "                            \"AddWindowsAppLink\": false,\r\n"
				+ "                            \"AllowDelegation\": true,\r\n"
				+ "                            \"AllowAccessFinishedWorkstep\": false,\r\n"
				+ "                            \"SkipExternalDataValidation\": false,\r\n"
				+ "                            \"AuthenticationMethods\": [],\r\n"
				+ "                            \"RemoteCertificateData\": {\r\n"
				+ "                                \"UserId\": \""+userId+"\",\r\n"
				+ "                                \"DeviceId\": \""+deviceID+"\"\r\n"
				+ "                            }\r\n"
				+ "                        }\r\n"
				+ "                    ],\r\n"
				+ "                    \"EmailBodyExtra\": \"\",\r\n"
				+ "                    \"RecipientType\": \"Signer\",\r\n"
				+ "                    \"WorkstepConfiguration\": {\r\n"
				+ "                        \"WorkstepLabel\": \"szerzodes\",\r\n"
				+ "                        \"SmallTextZoomFactorPercent\": 100,\r\n"
				+ "                        \"FinishAction\": {\r\n"
				+ "                            \"ServerActions\": [],\r\n"
				+ "                            \"ClientActions\": []\r\n"
				+ "                        },\r\n"
				+ "                        \"ReceiverInformation\": {\r\n"
				+ "                            \"UserInformation\": {\r\n"
				+ "                                \"FirstName\": \""+r2FirstName+"\",\r\n"
				+ "                                \"LastName\": \""+r2LastName+"\",\r\n"
				+ "                                \"EMail\": \""+r2Email+"\"\r\n"
				+ "                            },\r\n"
				+ "                            \"TransactionCodePushPluginData\": []\r\n"
				+ "                        },\r\n"
				+ "                        \"SenderInformation\": {\r\n"
				+ "                            \"UserInformation\": {\r\n"
				+ "                                \"FirstName\": \""+r2FirstName+"\",\r\n"
				+ "                                \"LastName\": \""+r2LastName+"\",\r\n"
				+ "                                \"EMail\": \""+r2Email+"\"\r\n"
				+ "                            }\r\n"
				+ "                        },\r\n"
				+ "                        \"TransactionCodeConfigurations\": [],\r\n"
				+ "                        \"SignatureConfigurations\": [],\r\n"
				+ "                        \"ViewerPreferences\": {\r\n"
				+ "                            \"FinishWorkstepOnOpen\": false,\r\n"
				+ "                            \"VisibleAreaOptions\": {\r\n"
				+ "                                \"AllowedDomain\": \"*\",\r\n"
				+ "                                \"Enabled\": false\r\n"
				+ "                            }\r\n"
				+ "                        },\r\n"
				+ "                        \"ResourceUris\": {\r\n"
				+ "                            \"DelegationUri\": \"https://demo.esignanywhere.net/Resource/Delegate\"\r\n"
				+ "                        },\r\n"
				+ "                        \"AdditionalClientWorkstepInformation\": \"<metaData />\",\r\n"
				+ "                        \"AuditingToolsConfiguration\": {\r\n"
				+ "                            \"WriteAuditTrail\": true,\r\n"
				+ "                            \"NotificationConfiguration\": {}\r\n"
				+ "                        },\r\n"
				+ "                        \"Policy\": {\r\n"
				+ "                            \"GeneralPolicies\": {\r\n"
				+ "                                \"AllowSaveDocument\": true,\r\n"
				+ "                                \"AllowSaveAuditTrail\": true,\r\n"
				+ "                                \"AllowRotatingPages\": false,\r\n"
				+ "                                \"AllowEmailDocument\": true,\r\n"
				+ "                                \"AllowPrintDocument\": true,\r\n"
				+ "                                \"AllowFinishWorkstep\": true,\r\n"
				+ "                                \"AllowRejectWorkstep\": true,\r\n"
				+ "                                \"AllowRejectWorkstepDelegation\": true,\r\n"
				+ "                                \"AllowUndoLastAction\": false,\r\n"
				+ "                                \"AllowAdhocPdfAttachments\": false,\r\n"
				+ "                                \"AllowAdhocSignatures\": false,\r\n"
				+ "                                \"AllowAdhocStampings\": false,\r\n"
				+ "                                \"AllowAdhocFreeHandAnnotations\": false,\r\n"
				+ "                                \"AllowAdhocTypewriterAnnotations\": false,\r\n"
				+ "                                \"AllowAdhocPictureAnnotations\": false,\r\n"
				+ "                                \"AllowAdhocPdfPageAppending\": false\r\n"
				+ "                            },\r\n"
				+ "                            \"WorkstepTasks\": {\r\n"
				+ "                                \"PictureAnnotationMinResolution\": 0,\r\n"
				+ "                                \"PictureAnnotationMaxResolution\": 0,\r\n"
				+ "                                \"PictureAnnotationColorDepth\": \"Color16M\",\r\n"
				+ "                                \"SequenceMode\": \"NoSequenceEnforced\",\r\n"
				+ "                                \"PositionUnits\": \"PdfUnits\",\r\n"
				+ "                                \"ReferenceCorner\": \"Lower_Left\",\r\n"
				+ "                                \"Tasks\": [\r\n"
				+ "                                    {\r\n"
				+ "                                        \"PositionPage\": 2,\r\n"
				+ "                                        \"Position\": {\r\n"
				+ "                                            \"PositionX\": 337.0,\r\n"
				+ "                                            \"PositionY\": 683.92\r\n"
				+ "                                        },\r\n"
				+ "                                        \"Size\": {\r\n"
				+ "                                            \"Height\": 72.0,\r\n"
				+ "                                            \"Width\": 190.0\r\n"
				+ "                                        },\r\n"
				+ "                                        \"AdditionalParameters\": [\r\n"
				+ "                                            {\r\n"
				+ "                                                \"Key\": \"enabled\",\r\n"
				+ "                                                \"Value\": \"1\"\r\n"
				+ "                                            },\r\n"
				+ "                                            {\r\n"
				+ "                                                \"Key\": \"positioning\",\r\n"
				+ "                                                \"Value\": \"onPage\"\r\n"
				+ "                                            },\r\n"
				+ "                                            {\r\n"
				+ "                                                \"Key\": \"req\",\r\n"
				+ "                                                \"Value\": \"1\"\r\n"
				+ "                                            },\r\n"
				+ "                                            {\r\n"
				+ "                                                \"Key\": \"fd\",\r\n"
				+ "                                                \"Value\": \"\"\r\n"
				+ "                                            },\r\n"
				+ "                                            {\r\n"
				+ "                                                \"Key\": \"fd_dateformat\",\r\n"
				+ "                                                \"Value\": \"dd-MM-yyyy HH:mm:ss\"\r\n"
				+ "                                            },\r\n"
				+ "                                            {\r\n"
				+ "                                                \"Key\": \"fd_timezone\",\r\n"
				+ "                                                \"Value\": \"datetimeutc\"\r\n"
				+ "                                            },\r\n"
				+ "                                            {\r\n"
				+ "                                                \"Key\": \"spcId\",\r\n"
				+ "                                                \"Value\": \"ltaLevelId\"\r\n"
				+ "                                            }\r\n"
				+ "                                        ],\r\n"
				+ "                                        \"AllowedSignatureTypes\": [\r\n"
				+ "                                            {\r\n"
				+ "                                                \"TrModType\": \"RemoteSignature\",\r\n"
				+ "                                                \"TrValidityInSeconds\": 300,\r\n"
				+ "                                                \"TrConfId\": \"remoteCertificateSignSmsText\",\r\n"
				+ "                                                \"IsPhoneNumberRequired\": false,\r\n"
				+ "                                                \"Ly\": \"remoteCertificate\",\r\n"
				+ "                                                \"Id\": \"5495f762-2e12-497f-8a9f-153ef725065f\",\r\n"
				+ "                                                \"DiscriminatorType\": \"SigTypeTransactionCode\",\r\n"
				+ "                                                \"Preferred\": false,\r\n"
				+ "                                                \"StampImprintConfiguration\": {\r\n"
				+ "                                                    \"DisplayExtraInformation\": true,\r\n"
				+ "                                                    \"DisplayEmail\": true,\r\n"
				+ "                                                    \"DisplayIp\": true,\r\n"
				+ "                                                    \"DisplayName\": true,\r\n"
				+ "                                                    \"DisplaySignatureDate\": true,\r\n"
				+ "                                                    \"FontFamily\": \"Times New Roman\",\r\n"
				+ "                                                    \"FontSize\": 11.0\r\n"
				+ "                                                }\r\n"
				+ "                                            }\r\n"
				+ "                                        ],\r\n"
				+ "                                        \"UseTimestamp\": false,\r\n"
				+ "                                        \"IsRequired\": true,\r\n"
				+ "                                        \"Id\": \"1#XyzmoDuplicateIdSeperator#Signature_f70918e6-d99e-02e6-69ac-5b9fe1c13877\",\r\n"
				+ "                                        \"DisplayName\": \"\",\r\n"
				+ "                                        \"DocRefNumber\": 1,\r\n"
				+ "                                        \"DiscriminatorType\": \"Signature\"\r\n"
				+ "                                    }\r\n"
				+ "                                ]\r\n"
				+ "                            },\r\n"
				+ "                            \"FinalizeActions\": {\r\n"
				+ "                                \"FinalizeActionList\": [\r\n"
				+ "                                    {\r\n"
				+ "                                        \"DocRefNumbers\": \"*\",\r\n"
				+ "                                        \"SpcId\": \"ltaLevelId\",\r\n"
				+ "                                        \"DiscriminatorType\": \"Timestamp\"\r\n"
				+ "                                    }\r\n"
				+ "                                ]\r\n"
				+ "                            }\r\n"
				+ "                        },\r\n"
				+ "                        \"Navigation\": {\r\n"
				+ "                            \"HyperLinks\": [],\r\n"
				+ "                            \"Links\": [],\r\n"
				+ "                            \"LinkTargets\": []\r\n"
				+ "                        }\r\n"
				+ "                    },\r\n"
				+ "                    \"DocumentOptions\": [\r\n"
				+ "                        {\r\n"
				+ "                            \"DocumentReference\": \"1\",\r\n"
				+ "                            \"IsHidden\": false\r\n"
				+ "                        }\r\n"
				+ "                    ],\r\n"
				+ "                    \"UseDefaultAgreements\": true\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"OrderIndex\": 3,\r\n"
				+ "                    \"Recipients\": [\r\n"
				+ "                        {\r\n"
				+ "                            \"Email\": \""+r1Email+"\",\r\n"
				+ "                            \"FirstName\": \""+r1FirstName+"\",\r\n"
				+ "                            \"LastName\": \""+r1LastName+"\",\r\n"
				+ "                            \"LanguageCode\": \"en\",\r\n"
				+ "                            \"EmailBodyExtra\": \"\",\r\n"
				+ "                            \"DisableEmail\": false,\r\n"
				+ "                            \"AddAndroidAppLink\": false,\r\n"
				+ "                            \"AddIosAppLink\": false,\r\n"
				+ "                            \"AddWindowsAppLink\": false,\r\n"
				+ "                            \"AllowDelegation\": false,\r\n"
				+ "                            \"AllowAccessFinishedWorkstep\": false,\r\n"
				+ "                            \"SkipExternalDataValidation\": false,\r\n"
				+ "                            \"AuthenticationMethods\": []\r\n"
				+ "                        }\r\n"
				+ "                    ],\r\n"
				+ "                    \"EmailBodyExtra\": \"\",\r\n"
				+ "                    \"RecipientType\": \"Cc\",\r\n"
				+ "                    \"DocumentOptions\": [\r\n"
				+ "                        {\r\n"
				+ "                            \"DocumentReference\": \"1\",\r\n"
				+ "                            \"IsHidden\": false\r\n"
				+ "                        }\r\n"
				+ "                    ],\r\n"
				+ "                    \"UseDefaultAgreements\": false\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"OrderIndex\": 4,\r\n"
				+ "                    \"Recipients\": [\r\n"
				+ "                        {\r\n"
				+ "                            \"Email\": \""+r2Email+"\",\r\n"
				+ "                            \"FirstName\": \""+r2FirstName+"\",\r\n"
				+ "                            \"LastName\": \""+r2LastName+"\",\r\n"
				+ "                            \"LanguageCode\": \"en\",\r\n"
				+ "                            \"EmailBodyExtra\": \"\",\r\n"
				+ "                            \"DisableEmail\": false,\r\n"
				+ "                            \"AddAndroidAppLink\": false,\r\n"
				+ "                            \"AddIosAppLink\": false,\r\n"
				+ "                            \"AddWindowsAppLink\": false,\r\n"
				+ "                            \"AllowDelegation\": false,\r\n"
				+ "                            \"AllowAccessFinishedWorkstep\": false,\r\n"
				+ "                            \"SkipExternalDataValidation\": false,\r\n"
				+ "                            \"AuthenticationMethods\": []\r\n"
				+ "                        }\r\n"
				+ "                    ],\r\n"
				+ "                    \"EmailBodyExtra\": \"\",\r\n"
				+ "                    \"RecipientType\": \"Cc\",\r\n"
				+ "                    \"DocumentOptions\": [\r\n"
				+ "                        {\r\n"
				+ "                            \"DocumentReference\": \"1\",\r\n"
				+ "                            \"IsHidden\": false\r\n"
				+ "                        }\r\n"
				+ "                    ],\r\n"
				+ "                    \"UseDefaultAgreements\": false\r\n"
				+ "                }\r\n"
				+ "            ],\r\n"
				+ "            \"AddFormFields\": {\r\n"
				+ "                \"Forms\": {}\r\n"
				+ "            },\r\n"
				+ "            \"OverrideFormFieldValues\": {\r\n"
				+ "                \"Forms\": {}\r\n"
				+ "            },\r\n"
				+ "            \"AttachSignedDocumentsToEnvelopeLog\": false\r\n"
				+ "        }\r\n"
				+ "    }";
	}

}
