package com.Contum.Integration.models;

public class order1s extends sendEnvelopeBase{

	public static String r1PhoneMobile;
	public static String signX;
	public static String signY;
	
	
	
	public static String getR1PhoneMobile() {
		return r1PhoneMobile;
	}



	public static void setR1PhoneMobile(String r1PhoneMobile) {
		order1s.r1PhoneMobile = r1PhoneMobile;
	}


	public static String getSignX() {
		return signX;
	}



	public static void setSignX(String signX) {
		order1s.signX = signX;
	}



	public static String getSignY() {
		return signY;
	}



	public static void setSignY(String signY) {
		order1s.signY = signY;
	}


	public static void setParameters(String envelopeName, String r1Email, String r1FirstName, String r1LastName, String r1phone,String signX, String signY) {
		setEnvelopeName(envelopeName);
		setR1Email(r1Email);
		setR1FirstName(r1FirstName);
		setR1LastName(r1LastName);
		setR1PhoneMobile(r1phone);
		setSignX(signX);
		setSignY(signY);
	}
		


	public static String getRequest() {
		return "{\r\n"
				+ "    \r\n"
				+ "    \"SspFileIds\": [\r\n \""+sspFileId+"\"\r\n"
				+ "    ],\r\n"
				+ "   \"SendEnvelopeDescription\": { \r\n"
				+ "  \"Name\": \""+envelopeName+"\",\r\n"
				+ "  \"EmailSubject\": \"Please sign the enclosed envelope\",\r\n"
				+ "  \"EmailBody\": \"Dear #RecipientFirstName# #RecipientLastName#\\n\\n#PersonalMessage#\\n\\nPlease sign the envelope #EnvelopeName#\\n\\nEnvelope will expire at #ExpirationDate#\",\r\n"
				+ "  \"DisplayedEmailSender\": \"\",\r\n"
				+ "  \"EnableReminders\": true,\r\n"
				+ "  \"FirstReminderDayAmount\": 5,\r\n"
				+ "  \"RecurrentReminderDayAmount\": 3,\r\n"
				+ "  \"BeforeExpirationDayAmount\": 3,\r\n"
				+ "  \"ExpirationInSecondsAfterSending\": 2419200,\r\n"
				+ "  \"CallbackUrl\": \"\",\r\n"
				+ "  \"StatusUpdateCallbackUrl\": \"\",\r\n"
				+ "  \"LockFormFieldsAtEnvelopeFinish\": false,\r\n"
				+ "  \"Steps\": [\r\n"
				+ "    {\r\n"
				+ "      \"OrderIndex\": 1,\r\n"
				+ "      \"Recipients\": [\r\n"
				+ "        {\r\n"
				+ "          \"Email\": \""+r1Email+"\",\r\n"
				+ "          \"FirstName\": \""+r1FirstName+"\",\r\n"
				+ "          \"LastName\": \""+r1LastName+"\",\r\n"
				+ "          \"LanguageCode\": \"en\",\r\n"
				+ "          \"EmailBodyExtra\": \"\",\r\n"
				+ "          \"DisableEmail\": false,\r\n"
				+ "          \"AddAndroidAppLink\": false,\r\n"
				+ "          \"AddIosAppLink\": false,\r\n"
				+ "          \"AddWindowsAppLink\": false,\r\n"
				+ "          \"AllowDelegation\": true,\r\n"
				+ "          \"AllowAccessFinishedWorkstep\": false,\r\n"
				+ "          \"SkipExternalDataValidation\": false,\r\n"
				+ "          \"AuthenticationMethods\": [\r\n"
				+ "            {\r\n"
				+ "              \"Method\": \"Sms\",\r\n"
				+ "              \"Parameter\": \""+r1PhoneMobile+"\"\r\n"
				+ "            }\r\n"
				+ "          ]\r\n"
				+ "        }\r\n"
				+ "      ],\r\n"
				+ "      \"EmailBodyExtra\": \"\",\r\n"
				+ "      \"RecipientType\": \"Signer\",\r\n"
				+ "      \"WorkstepConfiguration\": {\r\n"
				+ "        \"WorkstepLabel\": \"Megrendelőlap-1si.pdf\",\r\n"
				+ "        \"SmallTextZoomFactorPercent\": 100,\r\n"
				+ "        \"FinishAction\": {\r\n"
				+ "          \"ServerActions\": [],\r\n"
				+ "          \"ClientActions\": []\r\n"
				+ "        },\r\n"
				+ "        \"ReceiverInformation\": {\r\n"
				+ "          \"UserInformation\": {\r\n"
				+ "            \"FirstName\": \""+r1FirstName+"\",\r\n"
				+ "            \"LastName\": \""+r1LastName+"\",\r\n"
				+ "            \"EMail\": \""+r1Email+"\"\r\n"
				+ "          },\r\n"
				+ "          \"TransactionCodePushPluginData\": []\r\n"
				+ "        },\r\n"
				+ "        \"SenderInformation\": {\r\n"
				+ "          \"UserInformation\": {\r\n"
				+ "            \"FirstName\": \"Bence\",\r\n"
				+ "            \"LastName\": \"Katona\",\r\n"
				+ "            \"EMail\": \"katonabenyo@gmail.com\"\r\n"
				+ "          }\r\n"
				+ "        },\r\n"
				+ "        \"TransactionCodeConfigurations\": [],\r\n"
				+ "        \"SignatureConfigurations\": [],\r\n"
				+ "        \"ViewerPreferences\": {\r\n"
				+ "          \"FinishWorkstepOnOpen\": false,\r\n"
				+ "          \"VisibleAreaOptions\": {\r\n"
				+ "            \"AllowedDomain\": \"*\",\r\n"
				+ "            \"Enabled\": false\r\n"
				+ "          }\r\n"
				+ "        },\r\n"
				+ "        \"ResourceUris\": {\r\n"
				+ "          \"DelegationUri\": \"https://demo.esignanywhere.net/Resource/Delegate\"\r\n"
				+ "        },\r\n"
				+ "        \"AdditionalClientWorkstepInformation\": \"<metaData />\",\r\n"
				+ "        \"AuditingToolsConfiguration\": {\r\n"
				+ "          \"WriteAuditTrail\": false,\r\n"
				+ "          \"NotificationConfiguration\": {}\r\n"
				+ "        },\r\n"
				+ "        \"Policy\": {\r\n"
				+ "          \"GeneralPolicies\": {\r\n"
				+ "            \"AllowSaveDocument\": true,\r\n"
				+ "            \"AllowSaveAuditTrail\": true,\r\n"
				+ "            \"AllowRotatingPages\": false,\r\n"
				+ "            \"AllowEmailDocument\": true,\r\n"
				+ "            \"AllowPrintDocument\": true,\r\n"
				+ "            \"AllowFinishWorkstep\": true,\r\n"
				+ "            \"AllowRejectWorkstep\": true,\r\n"
				+ "            \"AllowRejectWorkstepDelegation\": true,\r\n"
				+ "            \"AllowUndoLastAction\": false,\r\n"
				+ "            \"AllowAdhocPdfAttachments\": false,\r\n"
				+ "            \"AllowAdhocSignatures\": false,\r\n"
				+ "            \"AllowAdhocStampings\": false,\r\n"
				+ "            \"AllowAdhocFreeHandAnnotations\": false,\r\n"
				+ "            \"AllowAdhocTypewriterAnnotations\": false,\r\n"
				+ "            \"AllowAdhocPictureAnnotations\": false,\r\n"
				+ "            \"AllowAdhocPdfPageAppending\": false\r\n"
				+ "          },\r\n"
				+ "          \"WorkstepTasks\": {\r\n"
				+ "            \"PictureAnnotationMinResolution\": 0,\r\n"
				+ "            \"PictureAnnotationMaxResolution\": 0,\r\n"
				+ "            \"PictureAnnotationColorDepth\": \"Color16M\",\r\n"
				+ "            \"SequenceMode\": \"NoSequenceEnforced\",\r\n"
				+ "            \"PositionUnits\": \"PdfUnits\",\r\n"
				+ "            \"ReferenceCorner\": \"Lower_Left\",\r\n"
				+ "            \"Tasks\": [\r\n"
				+ "              {\r\n"
				+ "                \"PageNumber\": 1,\r\n"
				+ "                \"TextAlign\": \"Left\",\r\n"
				+ "                \"Position\": {\r\n"
				+ "                  \"PositionX\": 100.0,\r\n"
				+ "                  \"PositionY\": 81.0\r\n"
				+ "                },\r\n"
				+ "                \"DefaultText\": \"##ReceiverFirstName## ##ReceiverLastName##\",\r\n"
				+ "                \"TextFormat\": \"\",\r\n"
				+ "                \"DefaultTextType\": \"FullName\",\r\n"
				+ "                \"FontSettings\": {\r\n"
				+ "                  \"Id\": \"440cc6fa-1cc7-47e6-ae29-425c91531386\",\r\n"
				+ "                  \"TextColor\": {\r\n"
				+ "                    \"A\": 255,\r\n"
				+ "                    \"R\": 0,\r\n"
				+ "                    \"G\": 0,\r\n"
				+ "                    \"B\": 0\r\n"
				+ "                  },\r\n"
				+ "                  \"Name\": \"Times New Roman\",\r\n"
				+ "                  \"Size\": 11.0,\r\n"
				+ "                  \"IsBold\": false,\r\n"
				+ "                  \"IsItalic\": false\r\n"
				+ "                },\r\n"
				+ "                \"IsEditablePosition\": false,\r\n"
				+ "                \"IsEditableDefaultText\": false,\r\n"
				+ "                \"IsEditableFontSettings\": false,\r\n"
				+ "                \"IsRequired\": false,\r\n"
				+ "                \"Id\": \"44349094-5dd9-48ac-bf86-7ca353792295\",\r\n"
				+ "                \"DocRefNumber\": 1,\r\n"
				+ "                \"DiscriminatorType\": \"TypewriterAnnotation\"\r\n"
				+ "              },\r\n"
				+ "              {\r\n"
				+ "                \"PageNumber\": 1,\r\n"
				+ "                \"TextAlign\": \"Left\",\r\n"
				+ "                \"Position\": {\r\n"
				+ "                  \"PositionX\": 101.0,\r\n"
				+ "                  \"PositionY\": 62.0\r\n"
				+ "                },\r\n"
				+ "                \"DefaultText\": \"##ClientTime##\",\r\n"
				+ "                \"TextFormat\": \"dd/MM/yyyy\",\r\n"
				+ "                \"DefaultTextType\": \"DateTime\",\r\n"
				+ "                \"FontSettings\": {\r\n"
				+ "                  \"Id\": \"440cc6fa-1cc7-47e6-ae29-425c91531386\",\r\n"
				+ "                  \"TextColor\": {\r\n"
				+ "                    \"A\": 255,\r\n"
				+ "                    \"R\": 0,\r\n"
				+ "                    \"G\": 0,\r\n"
				+ "                    \"B\": 0\r\n"
				+ "                  },\r\n"
				+ "                  \"Name\": \"Times New Roman\",\r\n"
				+ "                  \"Size\": 11.0,\r\n"
				+ "                  \"IsBold\": false,\r\n"
				+ "                  \"IsItalic\": false\r\n"
				+ "                },\r\n"
				+ "                \"IsEditablePosition\": false,\r\n"
				+ "                \"IsEditableDefaultText\": false,\r\n"
				+ "                \"IsEditableFontSettings\": false,\r\n"
				+ "                \"IsRequired\": false,\r\n"
				+ "                \"Id\": \"d41c6ac0-e7e9-414d-afa6-bf80da4caaa1\",\r\n"
				+ "                \"DocRefNumber\": 1,\r\n"
				+ "                \"DiscriminatorType\": \"TypewriterAnnotation\"\r\n"
				+ "              },\r\n"
				+ "              {\r\n"
				+ "                \"Forms\": [\r\n"
				+ "                  {\r\n"
				+ "                    \"IsRequired\": true,\r\n"
				+ "                    \"Id\": \"TextBox_CustomerName\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 162.0,\r\n"
				+ "                      \"PositionY\": 676.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 20.0,\r\n"
				+ "                      \"Width\": 358.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"TextBox\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"IsRequired\": true,\r\n"
				+ "                    \"Id\": \"TextBox_CustomerAddress\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 163.0,\r\n"
				+ "                      \"PositionY\": 653.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 20.0,\r\n"
				+ "                      \"Width\": 358.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"TextBox\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"IsRequired\": true,\r\n"
				+ "                    \"Id\": \"TextBox_CustomerMobile\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 140.0,\r\n"
				+ "                      \"PositionY\": 631.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 20.0,\r\n"
				+ "                      \"Width\": 382.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"TextBox\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"IsRequired\": true,\r\n"
				+ "                    \"Id\": \"TextBox_CustomerEmail\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 109.0,\r\n"
				+ "                      \"PositionY\": 607.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 20.0,\r\n"
				+ "                      \"Width\": 412.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"TextBox\"\r\n"
				+ "                  }\r\n"
				+ "                ],\r\n"
				+ "                \"IsRequired\": true,\r\n"
				+ "                \"Id\": \"4259ac65-42b1-420d-85c8-7c17216bdedb\",\r\n"
				+ "                \"DisplayName\": \"\",\r\n"
				+ "                \"DocRefNumber\": 1,\r\n"
				+ "                \"DiscriminatorType\": \"FormGroup\"\r\n"
				+ "              },\r\n"
				+ "              {\r\n"
				+ "                \"Forms\": [\r\n"
				+ "                  {\r\n"
				+ "                    \"RadioButtonGroupId\": \"RadioButton_fade00eb-e927-4c60-d7b8-b16c0acd7dd1\",\r\n"
				+ "                    \"IsRequired\": false,\r\n"
				+ "                    \"Id\": \"0\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 273.0,\r\n"
				+ "                      \"PositionY\": 529.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 20.0,\r\n"
				+ "                      \"Width\": 20.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"RadioButton\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"IsRequired\": false,\r\n"
				+ "                    \"Items\": [],\r\n"
				+ "                    \"Id\": \"ComboBox_USB64GB\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 355.0,\r\n"
				+ "                      \"PositionY\": 529.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 26.0,\r\n"
				+ "                      \"Width\": 109.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"ComboBox\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"RadioButtonGroupId\": \"RadioButton_242b95a5-fc38-3922-729a-ecde89823845\",\r\n"
				+ "                    \"IsRequired\": false,\r\n"
				+ "                    \"Id\": \"0\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 273.0,\r\n"
				+ "                      \"PositionY\": 505.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 20.0,\r\n"
				+ "                      \"Width\": 20.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"RadioButton\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"IsRequired\": false,\r\n"
				+ "                    \"Items\": [],\r\n"
				+ "                    \"Id\": \"ComboBox_USB128GB\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 355.0,\r\n"
				+ "                      \"PositionY\": 502.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 26.0,\r\n"
				+ "                      \"Width\": 109.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"ComboBox\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"RadioButtonGroupId\": \"RadioButton_4febf626-0943-cc06-5708-7b8b0b935b36\",\r\n"
				+ "                    \"IsRequired\": false,\r\n"
				+ "                    \"Id\": \"0\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 273.0,\r\n"
				+ "                      \"PositionY\": 478.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 20.0,\r\n"
				+ "                      \"Width\": 20.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"RadioButton\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"IsRequired\": false,\r\n"
				+ "                    \"Items\": [],\r\n"
				+ "                    \"Id\": \"ComboBox_SSD512GB\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 355.0,\r\n"
				+ "                      \"PositionY\": 475.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 26.0,\r\n"
				+ "                      \"Width\": 109.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"ComboBox\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"RadioButtonGroupId\": \"RadioButton_3c88418a-178f-9539-2f30-b93bc7ebeff6\",\r\n"
				+ "                    \"IsRequired\": false,\r\n"
				+ "                    \"Id\": \"0\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 273.0,\r\n"
				+ "                      \"PositionY\": 451.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 19.0,\r\n"
				+ "                      \"Width\": 20.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"RadioButton\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"IsRequired\": false,\r\n"
				+ "                    \"Items\": [],\r\n"
				+ "                    \"Id\": \"ComboBox_SSD1TB\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 355.0,\r\n"
				+ "                      \"PositionY\": 446.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 26.0,\r\n"
				+ "                      \"Width\": 109.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"ComboBox\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"RadioButtonGroupId\": \"RadioButton_09c343c8-bf21-5942-f4bb-97328ade9401\",\r\n"
				+ "                    \"IsRequired\": false,\r\n"
				+ "                    \"Id\": \"0\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 273.0,\r\n"
				+ "                      \"PositionY\": 422.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 19.0,\r\n"
				+ "                      \"Width\": 19.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"RadioButton\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"IsRequired\": false,\r\n"
				+ "                    \"Items\": [],\r\n"
				+ "                    \"Id\": \"ComboBox_HDD512GB\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 355.0,\r\n"
				+ "                      \"PositionY\": 419.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 26.0,\r\n"
				+ "                      \"Width\": 109.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"ComboBox\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"RadioButtonGroupId\": \"RadioButton_3b09b570-c611-da6e-4d75-671af03a5c37\",\r\n"
				+ "                    \"IsRequired\": false,\r\n"
				+ "                    \"Id\": \"0\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 273.0,\r\n"
				+ "                      \"PositionY\": 391.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 19.0,\r\n"
				+ "                      \"Width\": 19.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"RadioButton\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"IsRequired\": false,\r\n"
				+ "                    \"Items\": [],\r\n"
				+ "                    \"Id\": \"ComboBox_HDD1TB\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 355.0,\r\n"
				+ "                      \"PositionY\": 390.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 26.0,\r\n"
				+ "                      \"Width\": 109.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"ComboBox\"\r\n"
				+ "                  }\r\n"
				+ "                ],\r\n"
				+ "                \"IsRequired\": false,\r\n"
				+ "                \"Id\": \"bae386ac-3cc2-4c90-a80d-9a64d0cebecf\",\r\n"
				+ "                \"DisplayName\": \"\",\r\n"
				+ "                \"DocRefNumber\": 1,\r\n"
				+ "                \"DiscriminatorType\": \"FormGroup\"\r\n"
				+ "              },\r\n"
				+ "              {\r\n"
				+ "                \"Forms\": [\r\n"
				+ "                  {\r\n"
				+ "                    \"IsRequired\": true,\r\n"
				+ "                    \"RequiredEvalPolicy\": \"IsChecked\",\r\n"
				+ "                    \"Id\": \"CheckBox_b3112e0b-e2b4-269a-8ed7-7b8aa6d9839c\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 73.0,\r\n"
				+ "                      \"PositionY\": 351.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 19.0,\r\n"
				+ "                      \"Width\": 20.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"CheckBox\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"IsRequired\": true,\r\n"
				+ "                    \"RequiredEvalPolicy\": \"IsChecked\",\r\n"
				+ "                    \"Id\": \"CheckBox_c9b0cd9a-7895-2b38-4508-b3a2a7f48864\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 73.0,\r\n"
				+ "                      \"PositionY\": 327.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 19.0,\r\n"
				+ "                      \"Width\": 19.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"CheckBox\"\r\n"
				+ "                  }\r\n"
				+ "                ],\r\n"
				+ "                \"IsRequired\": true,\r\n"
				+ "                \"Id\": \"c131fea0-96dc-46f9-9fa4-f59cf0ca2e22\",\r\n"
				+ "                \"DisplayName\": \"\",\r\n"
				+ "                \"DocRefNumber\": 1,\r\n"
				+ "                \"DiscriminatorType\": \"FormGroup\"\r\n"
				+ "              },\r\n"
				+ "              {\r\n"
				+ "                \"Forms\": [\r\n"
				+ "                  {\r\n"
				+ "                    \"IsRequired\": false,\r\n"
				+ "                    \"RequiredEvalPolicy\": \"None\",\r\n"
				+ "                    \"Id\": \"CheckBox_e6f772f1-6ba0-b81d-0f1f-565253fd96df\",\r\n"
				+ "                    \"PositionPage\": 1,\r\n"
				+ "                    \"DocRefNumber\": 1,\r\n"
				+ "                    \"Position\": {\r\n"
				+ "                      \"PositionX\": 73.0,\r\n"
				+ "                      \"PositionY\": 303.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Size\": {\r\n"
				+ "                      \"Height\": 19.0,\r\n"
				+ "                      \"Width\": 20.0\r\n"
				+ "                    },\r\n"
				+ "                    \"DiscriminatorType\": \"CheckBox\"\r\n"
				+ "                  }\r\n"
				+ "                ],\r\n"
				+ "                \"IsRequired\": false,\r\n"
				+ "                \"Id\": \"1918a453-ca1c-4f9d-a15f-ff56a6041d8b\",\r\n"
				+ "                \"DisplayName\": \"\",\r\n"
				+ "                \"DocRefNumber\": 1,\r\n"
				+ "                \"DiscriminatorType\": \"FormGroup\"\r\n"
				+ "              },\r\n"
				+ "              {\r\n"
				+ "                \"PositionPage\": 1,\r\n"
				+ "                \"Position\": {\r\n"
				+ "                  \"PositionX\": "+signX+",\r\n"
				+ "                  \"PositionY\": "+signY+"\r\n"
				+ "                },\r\n"
				+ "                \"Size\": {\r\n"
				+ "                  \"Height\": 80.0,\r\n"
				+ "                  \"Width\": 190.0\r\n"
				+ "                },\r\n"
				+ "                \"AdditionalParameters\": [\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"enabled\",\r\n"
				+ "                    \"Value\": \"1\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"positioning\",\r\n"
				+ "                    \"Value\": \"onPage\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"req\",\r\n"
				+ "                    \"Value\": \"1\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"fd\",\r\n"
				+ "                    \"Value\": \"\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"fd_dateformat\",\r\n"
				+ "                    \"Value\": \"dd-MM-yyyy HH:mm:ss\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"fd_timezone\",\r\n"
				+ "                    \"Value\": \"datetimeutc\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"spcId\",\r\n"
				+ "                    \"Value\": \"ltaLevelId\"\r\n"
				+ "                  }\r\n"
				+ "                ],\r\n"
				+ "                \"AllowedSignatureTypes\": [\r\n"
				+ "                  {\r\n"
				+ "                    \"AllowedCapturingMethod\": \"Click2Sign\",\r\n"
				+ "                    \"Id\": \"a768a46f-f5d2-4a8f-8823-59c9dde72b7e\",\r\n"
				+ "                    \"DiscriminatorType\": \"SigTypeClick2Sign\",\r\n"
				+ "                    \"Preferred\": false,\r\n"
				+ "                    \"StampImprintConfiguration\": {\r\n"
				+ "                      \"DisplayExtraInformation\": true,\r\n"
				+ "                      \"DisplayEmail\": true,\r\n"
				+ "                      \"DisplayIp\": true,\r\n"
				+ "                      \"DisplayName\": true,\r\n"
				+ "                      \"DisplaySignatureDate\": true,\r\n"
				+ "                      \"FontFamily\": \"Times New Roman\",\r\n"
				+ "                      \"FontSize\": 11.0\r\n"
				+ "                    }\r\n"
				+ "                  }\r\n"
				+ "                ],\r\n"
				+ "                \"UseTimestamp\": false,\r\n"
				+ "                \"IsRequired\": true,\r\n"
				+ "                \"Id\": \"1#XyzmoDuplicateIdSeperator#Signature_0bf82860-0e27-f178-f685-7cb6f4af39e7\",\r\n"
				+ "                \"DisplayName\": \"\",\r\n"
				+ "                \"DocRefNumber\": 1,\r\n"
				+ "                \"DiscriminatorType\": \"Signature\"\r\n"
				+ "              }\r\n"
				+ "            ]\r\n"
				+ "          },\r\n"
				+ "          \"FinalizeActions\": {\r\n"
				+ "            \"FinalizeActionList\": [\r\n"
				+ "              {\r\n"
				+ "                \"DocRefNumbers\": \"*\",\r\n"
				+ "                \"SpcId\": \"ltaLevelId\",\r\n"
				+ "                \"DiscriminatorType\": \"Timestamp\"\r\n"
				+ "              }\r\n"
				+ "            ]\r\n"
				+ "          }\r\n"
				+ "        },\r\n"
				+ "        \"Navigation\": {\r\n"
				+ "          \"HyperLinks\": [],\r\n"
				+ "          \"Links\": [],\r\n"
				+ "          \"LinkTargets\": []\r\n"
				+ "        }\r\n"
				+ "      },\r\n"
				+ "      \"DocumentOptions\": [\r\n"
				+ "        {\r\n"
				+ "          \"DocumentReference\": \"1\",\r\n"
				+ "          \"IsHidden\": false\r\n"
				+ "        }\r\n"
				+ "      ],\r\n"
				+ "      \"UseDefaultAgreements\": true\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"OrderIndex\": 2,\r\n"
				+ "      \"Recipients\": [\r\n"
				+ "        {\r\n"
				+ "          \"Email\": \""+r1Email+"\",\r\n"
				+ "          \"FirstName\": \""+r1FirstName+"\",\r\n"
				+ "          \"LastName\": \""+r1LastName+"\",\r\n"
				+ "          \"LanguageCode\": \"en\",\r\n"
				+ "          \"EmailBodyExtra\": \"\",\r\n"
				+ "          \"DisableEmail\": false,\r\n"
				+ "          \"AddAndroidAppLink\": false,\r\n"
				+ "          \"AddIosAppLink\": false,\r\n"
				+ "          \"AddWindowsAppLink\": false,\r\n"
				+ "          \"AllowDelegation\": false,\r\n"
				+ "          \"SkipExternalDataValidation\": false,\r\n"
				+ "          \"AuthenticationMethods\": []\r\n"
				+ "        }\r\n"
				+ "      ],\r\n"
				+ "      \"EmailBodyExtra\": \"\",\r\n"
				+ "      \"RecipientType\": \"Cc\",\r\n"
				+ "      \"DocumentOptions\": [],\r\n"
				+ "      \"UseDefaultAgreements\": false\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"AddFormFields\": {\r\n"
				+ "    \"Forms\": {\r\n"
				+ "      \"1\": [\r\n"
				+ "        {\r\n"
				+ "          \"Value\": \"0\",\r\n"
				+ "          \"Items\": [\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"0\",\r\n"
				+ "              \"DisplayValue\": \"0\",\r\n"
				+ "              \"IsSelected\": true\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"1\",\r\n"
				+ "              \"DisplayValue\": \"1\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"2\",\r\n"
				+ "              \"DisplayValue\": \"2\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"3\",\r\n"
				+ "              \"DisplayValue\": \"3\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            }\r\n"
				+ "          ],\r\n"
				+ "          \"TextColor\": \"\",\r\n"
				+ "          \"FontSize\": 11.0,\r\n"
				+ "          \"FontName\": \"Times New Roman\",\r\n"
				+ "          \"Bold\": false,\r\n"
				+ "          \"Italic\": false,\r\n"
				+ "          \"TextAlign\": \"Left\",\r\n"
				+ "          \"Name\": \"ComboBox_USB64GB\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 355.0,\r\n"
				+ "          \"Y\": 529.92,\r\n"
				+ "          \"Width\": 109.0,\r\n"
				+ "          \"Height\": 26.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddComboBoxFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"Value\": \"0\",\r\n"
				+ "          \"Items\": [\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"0\",\r\n"
				+ "              \"DisplayValue\": \"0\",\r\n"
				+ "              \"IsSelected\": true\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"1\",\r\n"
				+ "              \"DisplayValue\": \"1\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"2\",\r\n"
				+ "              \"DisplayValue\": \"2\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"3\",\r\n"
				+ "              \"DisplayValue\": \"3\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            }\r\n"
				+ "          ],\r\n"
				+ "          \"TextColor\": \"\",\r\n"
				+ "          \"FontSize\": 11.0,\r\n"
				+ "          \"FontName\": \"Times New Roman\",\r\n"
				+ "          \"Bold\": false,\r\n"
				+ "          \"Italic\": false,\r\n"
				+ "          \"TextAlign\": \"Left\",\r\n"
				+ "          \"Name\": \"ComboBox_USB128GB\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 355.0,\r\n"
				+ "          \"Y\": 502.92,\r\n"
				+ "          \"Width\": 109.0,\r\n"
				+ "          \"Height\": 26.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddComboBoxFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"Value\": \"0\",\r\n"
				+ "          \"Items\": [\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"0\",\r\n"
				+ "              \"DisplayValue\": \"0\",\r\n"
				+ "              \"IsSelected\": true\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"1\",\r\n"
				+ "              \"DisplayValue\": \"1\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"2\",\r\n"
				+ "              \"DisplayValue\": \"2\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"3\",\r\n"
				+ "              \"DisplayValue\": \"3\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            }\r\n"
				+ "          ],\r\n"
				+ "          \"TextColor\": \"\",\r\n"
				+ "          \"FontSize\": 11.0,\r\n"
				+ "          \"FontName\": \"Times New Roman\",\r\n"
				+ "          \"Bold\": false,\r\n"
				+ "          \"Italic\": false,\r\n"
				+ "          \"TextAlign\": \"Left\",\r\n"
				+ "          \"Name\": \"ComboBox_SSD512GB\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 355.0,\r\n"
				+ "          \"Y\": 475.92,\r\n"
				+ "          \"Width\": 109.0,\r\n"
				+ "          \"Height\": 26.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddComboBoxFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"ExportValue\": \"87059e36-8ac9-97c7-a062-88b53d8c1cae\",\r\n"
				+ "          \"IsChecked\": false,\r\n"
				+ "          \"Name\": \"RadioButton_4febf626-0943-cc06-5708-7b8b0b935b36\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 273.0,\r\n"
				+ "          \"Y\": 478.92,\r\n"
				+ "          \"Width\": 20.0,\r\n"
				+ "          \"Height\": 20.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddRadioButtonFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"ExportValue\": \"a31823a7-403f-873d-4952-c261ec505f85\",\r\n"
				+ "          \"IsChecked\": false,\r\n"
				+ "          \"Name\": \"RadioButton_242b95a5-fc38-3922-729a-ecde89823845\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 273.0,\r\n"
				+ "          \"Y\": 505.92,\r\n"
				+ "          \"Width\": 20.0,\r\n"
				+ "          \"Height\": 20.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddRadioButtonFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"ExportValue\": \"61f0e9bf-6b2d-4eb1-8cd0-c8fee6cfe7f2\",\r\n"
				+ "          \"IsChecked\": false,\r\n"
				+ "          \"Name\": \"RadioButton_fade00eb-e927-4c60-d7b8-b16c0acd7dd1\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 273.0,\r\n"
				+ "          \"Y\": 529.92,\r\n"
				+ "          \"Width\": 20.0,\r\n"
				+ "          \"Height\": 20.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddRadioButtonFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"Value\": \"0\",\r\n"
				+ "          \"Items\": [\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"0\",\r\n"
				+ "              \"DisplayValue\": \"0\",\r\n"
				+ "              \"IsSelected\": true\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"1\",\r\n"
				+ "              \"DisplayValue\": \"1\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"2\",\r\n"
				+ "              \"DisplayValue\": \"2\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"3\",\r\n"
				+ "              \"DisplayValue\": \"3\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            }\r\n"
				+ "          ],\r\n"
				+ "          \"TextColor\": \"\",\r\n"
				+ "          \"FontSize\": 11.0,\r\n"
				+ "          \"FontName\": \"Times New Roman\",\r\n"
				+ "          \"Bold\": false,\r\n"
				+ "          \"Italic\": false,\r\n"
				+ "          \"TextAlign\": \"Left\",\r\n"
				+ "          \"Name\": \"ComboBox_SSD1TB\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 355.0,\r\n"
				+ "          \"Y\": 446.92,\r\n"
				+ "          \"Width\": 109.0,\r\n"
				+ "          \"Height\": 26.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddComboBoxFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"Value\": \"0\",\r\n"
				+ "          \"Items\": [\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"0\",\r\n"
				+ "              \"DisplayValue\": \"0\",\r\n"
				+ "              \"IsSelected\": true\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"1\",\r\n"
				+ "              \"DisplayValue\": \"1\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"2\",\r\n"
				+ "              \"DisplayValue\": \"2\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"3\",\r\n"
				+ "              \"DisplayValue\": \"3\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            }\r\n"
				+ "          ],\r\n"
				+ "          \"TextColor\": \"\",\r\n"
				+ "          \"FontSize\": 11.0,\r\n"
				+ "          \"FontName\": \"Times New Roman\",\r\n"
				+ "          \"Bold\": false,\r\n"
				+ "          \"Italic\": false,\r\n"
				+ "          \"TextAlign\": \"Left\",\r\n"
				+ "          \"Name\": \"ComboBox_HDD512GB\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 355.0,\r\n"
				+ "          \"Y\": 419.92,\r\n"
				+ "          \"Width\": 109.0,\r\n"
				+ "          \"Height\": 26.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddComboBoxFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"Value\": \"0\",\r\n"
				+ "          \"Items\": [\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"0\",\r\n"
				+ "              \"DisplayValue\": \"0\",\r\n"
				+ "              \"IsSelected\": true\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"1\",\r\n"
				+ "              \"DisplayValue\": \"1\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"2\",\r\n"
				+ "              \"DisplayValue\": \"2\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "              \"ExportValue\": \"3\",\r\n"
				+ "              \"DisplayValue\": \"3\",\r\n"
				+ "              \"IsSelected\": false\r\n"
				+ "            }\r\n"
				+ "          ],\r\n"
				+ "          \"TextColor\": \"\",\r\n"
				+ "          \"FontSize\": 11.0,\r\n"
				+ "          \"FontName\": \"Times New Roman\",\r\n"
				+ "          \"Bold\": false,\r\n"
				+ "          \"Italic\": false,\r\n"
				+ "          \"TextAlign\": \"Left\",\r\n"
				+ "          \"Name\": \"ComboBox_HDD1TB\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 355.0,\r\n"
				+ "          \"Y\": 390.92,\r\n"
				+ "          \"Width\": 109.0,\r\n"
				+ "          \"Height\": 26.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddComboBoxFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"Value\": \"\",\r\n"
				+ "          \"MaxLength\": -1,\r\n"
				+ "          \"IsMultiline\": false,\r\n"
				+ "          \"IsPassword\": false,\r\n"
				+ "          \"IsComb\": false,\r\n"
				+ "          \"TextColor\": \"0, 0, 0\",\r\n"
				+ "          \"FontSize\": 11.0,\r\n"
				+ "          \"FontName\": \"Times New Roman\",\r\n"
				+ "          \"Bold\": false,\r\n"
				+ "          \"Italic\": false,\r\n"
				+ "          \"TextAlign\": \"Left\",\r\n"
				+ "          \"Name\": \"TextBox_CustomerName\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 163.0,\r\n"
				+ "          \"Y\": 678.92,\r\n"
				+ "          \"Width\": 358.0,\r\n"
				+ "          \"Height\": 20.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddTextBoxFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"Value\": \"\",\r\n"
				+ "          \"MaxLength\": -1,\r\n"
				+ "          \"IsMultiline\": false,\r\n"
				+ "          \"IsPassword\": false,\r\n"
				+ "          \"IsComb\": false,\r\n"
				+ "          \"TextColor\": \"0, 0, 0\",\r\n"
				+ "          \"FontSize\": 11.0,\r\n"
				+ "          \"FontName\": \"Times New Roman\",\r\n"
				+ "          \"Bold\": false,\r\n"
				+ "          \"Italic\": false,\r\n"
				+ "          \"TextAlign\": \"Left\",\r\n"
				+ "          \"Name\": \"TextBox_CustomerAddress\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 161.0,\r\n"
				+ "          \"Y\": 654.92,\r\n"
				+ "          \"Width\": 361.0,\r\n"
				+ "          \"Height\": 20.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddTextBoxFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"Value\": \"\",\r\n"
				+ "          \"MaxLength\": -1,\r\n"
				+ "          \"IsMultiline\": false,\r\n"
				+ "          \"IsPassword\": false,\r\n"
				+ "          \"IsComb\": false,\r\n"
				+ "          \"TextColor\": \"0, 0, 0\",\r\n"
				+ "          \"FontSize\": 11.0,\r\n"
				+ "          \"FontName\": \"Times New Roman\",\r\n"
				+ "          \"Bold\": false,\r\n"
				+ "          \"Italic\": false,\r\n"
				+ "          \"TextAlign\": \"Left\",\r\n"
				+ "          \"Name\": \"TextBox_CustomerMobile\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 138.0,\r\n"
				+ "          \"Y\": 632.92,\r\n"
				+ "          \"Width\": 384.0,\r\n"
				+ "          \"Height\": 20.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddTextBoxFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"Value\": \"\",\r\n"
				+ "          \"MaxLength\": -1,\r\n"
				+ "          \"IsMultiline\": false,\r\n"
				+ "          \"IsPassword\": false,\r\n"
				+ "          \"IsComb\": false,\r\n"
				+ "          \"TextColor\": \"0, 0, 0\",\r\n"
				+ "          \"FontSize\": 11.0,\r\n"
				+ "          \"FontName\": \"Times New Roman\",\r\n"
				+ "          \"Bold\": false,\r\n"
				+ "          \"Italic\": false,\r\n"
				+ "          \"TextAlign\": \"Left\",\r\n"
				+ "          \"Name\": \"TextBox_CustomerEmail\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 109.0,\r\n"
				+ "          \"Y\": 608.92,\r\n"
				+ "          \"Width\": 414.0,\r\n"
				+ "          \"Height\": 20.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddTextBoxFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"IsChecked\": false,\r\n"
				+ "          \"Name\": \"CheckBox_b3112e0b-e2b4-269a-8ed7-7b8aa6d9839c\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": true,\r\n"
				+ "          \"X\": 73.0,\r\n"
				+ "          \"Y\": 351.91999999999996,\r\n"
				+ "          \"Width\": 20.0,\r\n"
				+ "          \"Height\": 19.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddCheckBoxFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"IsChecked\": false,\r\n"
				+ "          \"Name\": \"CheckBox_c9b0cd9a-7895-2b38-4508-b3a2a7f48864\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": true,\r\n"
				+ "          \"X\": 73.0,\r\n"
				+ "          \"Y\": 327.91999999999996,\r\n"
				+ "          \"Width\": 19.0,\r\n"
				+ "          \"Height\": 19.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddCheckBoxFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"IsChecked\": false,\r\n"
				+ "          \"Name\": \"CheckBox_e6f772f1-6ba0-b81d-0f1f-565253fd96df\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 73.0,\r\n"
				+ "          \"Y\": 303.91999999999996,\r\n"
				+ "          \"Width\": 20.0,\r\n"
				+ "          \"Height\": 19.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddCheckBoxFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"ExportValue\": \"b4fceb41-2945-403f-abb8-449faf2ce669\",\r\n"
				+ "          \"IsChecked\": false,\r\n"
				+ "          \"Name\": \"RadioButton_3b09b570-c611-da6e-4d75-671af03a5c37\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 273.0,\r\n"
				+ "          \"Y\": 391.92,\r\n"
				+ "          \"Width\": 19.0,\r\n"
				+ "          \"Height\": 19.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddRadioButtonFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"ExportValue\": \"4809af63-ffc9-b7cd-549a-0cb32d7b458a\",\r\n"
				+ "          \"IsChecked\": false,\r\n"
				+ "          \"Name\": \"RadioButton_09c343c8-bf21-5942-f4bb-97328ade9401\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 273.0,\r\n"
				+ "          \"Y\": 422.92,\r\n"
				+ "          \"Width\": 19.0,\r\n"
				+ "          \"Height\": 19.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddRadioButtonFormFieldDescriptor\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"ExportValue\": \"76f38229-232a-0638-f7af-ad0336d1c3d3\",\r\n"
				+ "          \"IsChecked\": false,\r\n"
				+ "          \"Name\": \"RadioButton_3c88418a-178f-9539-2f30-b93bc7ebeff6\",\r\n"
				+ "          \"ReadOnly\": false,\r\n"
				+ "          \"Required\": false,\r\n"
				+ "          \"X\": 273.0,\r\n"
				+ "          \"Y\": 451.92,\r\n"
				+ "          \"Width\": 20.0,\r\n"
				+ "          \"Height\": 19.0,\r\n"
				+ "          \"Page\": 1,\r\n"
				+ "          \"DiscriminatorType\": \"AddRadioButtonFormFieldDescriptor\"\r\n"
				+ "        }\r\n"
				+ "      ]\r\n"
				+ "    }\r\n"
				+ "  },\r\n"
				+ "  \"OverrideFormFieldValues\": {\r\n"
				+ "    \"Forms\": {}\r\n"
				+ "  },\r\n"
				+ "  \"AttachSignedDocumentsToEnvelopeLog\": false\r\n"
				+ "   }\r\n"
				+ "   }\r\n"
				+ "";
	}

}
