package com.Contum.Integration.models;

public class prepareEnvelope {

	public static String request = "{\r\n"
			+ "  \"SspFileIds\":[\"\"],\r\n"
			+ "  \"AdHocWorkstepConfiguration\": {\r\n"
			+ "    \"WorkstepLabel\": \"workstepLabel\",\r\n"
			+ "    \"SmallTextZoomFactorPercent\": 100,\r\n"
			+ "    \"WorkstepTimeToLiveInMinutes\": 100000,\r\n"
			+ "    \"FinishAction\": {\r\n"
			+ "      \"ServerActions\": [\r\n"
			+ "        {\r\n"
			+ "          \"CallSynchronous\": true\r\n"
			+ "        }\r\n"
			+ "      ],\r\n"
			+ "      \"ClientActions\": [\r\n"
			+ "        {\r\n"
			+ "          \"RemoveDocumentFromRecentDocumentList\": true,\r\n"
			+ "          \"CallClientActionOnlyAfterSuccessfulSync\": true,\r\n"
			+ "          \"ClientName\": \"string\",\r\n"
			+ "          \"CloseApp\": true,\r\n"
			+ "          \"Action\": \"string\"\r\n"
			+ "        }\r\n"
			+ "      ]\r\n"
			+ "    },\r\n"
			+ "    \"NoSequenceEnforced\": false,\r\n"
			+ "    \"SigTemplate\": {\r\n"
			+ "      \"Size\": {\r\n"
			+ "        \"Height\": 68,\r\n"
			+ "        \"Width\": 171\r\n"
			+ "      },\r\n"
			+ "      \"AllowedSignatureTypes\": [\r\n"
			+ "        {\r\n"
			+ "          \"TrModType\": \"TransactionCodeSenderPlugin\",\r\n"
			+ "          \"TrValidityInSeconds\": 300,\r\n"
			+ "          \"Ly\": \"simpleTransactionCodeSms\",\r\n"
			+ "          \"TrConfId\": \"otpSignatureSmsText\",\r\n"
			+ "          \"IsPhoneNumberRequired\": true,\r\n"
			+ "          \"Id\": \"e80a4c7f-3492-4a56-ac47-1dec59dfb7ad\",\r\n"
			+ "          \"DiscriminatorType\": \"SigTypeTransactionCode\",\r\n"
			+ "          \"Preferred\": false,\r\n"
			+ "          \"StampImprintConfiguration\":\r\n"
			+ "          {\r\n"
			+ "            \"DisplayExtraInformation\": true,\r\n"
			+ "            \"DisplayEmail\": true,\r\n"
			+ "            \"DisplayIp\": true,\r\n"
			+ "            \"DisplayName\": true,\r\n"
			+ "            \"DisplaySignatureDate\": true,\r\n"
			+ "            \"FontFamily\": \"Times New Roman\",\r\n"
			+ "            \"FontSize\": 10,\r\n"
			+ "            \"OverrideLegacyStampImprint\": true,\r\n"
			+ "            \"DisplayTransactionId\": true,\r\n"
			+ "            \"DisplayTransaktionToken\": true,\r\n"
			+ "            \"DisplayPhoneNumber\": true\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "      ]\r\n"
			+ "    },\r\n"
			+ "    \"ParseFormFields\": {\r\n"
			+ "      \"MapRequiredFieldsToRequiredTask\": true,\r\n"
			+ "      \"FormsGrouping\": \"PerPage\",\r\n"
			+ "      \"ReturnSimplifiedConfig\": true,\r\n"
			+ "      \"AddKeepExistingValueFlag\": true,\r\n"
			+ "      \"ParseFormField\": true\r\n"
			+ "    },\r\n"
			+ "    \"AdhocPolicies\": {\r\n"
			+ "      \"AllowModificationsAfterSignature\": true\r\n"
			+ "    },\r\n"
			+ "    \"ViewerPreferences\": {\r\n"
			+ "      \"ShowPageNavigationBar\": true,\r\n"
			+ "      \"ShowThumbnails\": true,\r\n"
			+ "      \"SkipFinishConfirmDialog\": true,\r\n"
			+ "      \"SkipDocumentDialog\": true,\r\n"
			+ "      \"ShowImagesInFullWidth\": true,\r\n"
			+ "      \"DisableGeolocation\": true,\r\n"
			+ "      \"ShowDocumentDownloadDialogAfterAutomaticFinish\": true,\r\n"
			+ "      \"AttachmentsMaxFileSize\": 0,\r\n"
			+ "      \"SkipPreviewImageOnDisposableCertificate\": true,\r\n"
			+ "      \"LoadCustomJs\": true,\r\n"
			+ "      \"AllowCustomButtons\": true,\r\n"
			+ "      \"GuidingBehavior\": \"GuideOnlyRequiredTasks\",\r\n"
			+ "      \"FormFieldsGuidingBehavior\": \"AllowSubmitAlways\",\r\n"
			+ "      \"ShowVersionNumber\": true,\r\n"
			+ "      \"EnableWarningPopupOnLeave\": true,\r\n"
			+ "      \"WarningPopupDisplayAfter\": \"FillOrSignField\",\r\n"
			+ "      \"FinishWorkstepOnOpen\": true,\r\n"
			+ "      \"AutoFinishAfterRequiredTasksDone\": true,\r\n"
			+ "      \"GuidingBehaviorOnFinishedTask\": \"NoMove\",\r\n"
			+ "      \"SkipThankYouDialog\": true,\r\n"
			+ "      \"NativeAppsUrlScheme\": \"string\",\r\n"
			+ "      \"DocumentViewingMode\": \"EndlessPaperAllDocuments\",\r\n"
			+ "      \"ThumbnailMode\": \"ShowAllPages\",\r\n"
			+ "      \"ShowTopBar\": true,\r\n"
			+ "      \"DisplayRejectButtonInTopBar\": true,\r\n"
			+ "      \"MultipleSignatureTypesAndBatchSigningSettings\": {\r\n"
			+ "        \"IsUseBatchSigningCheckedByDefault\": true,\r\n"
			+ "        \"IsRememberSignatureTypeCheckedByDefault\": true,\r\n"
			+ "        \"IsRememberBatchSigningDecisionCheckedByDefault\": true,\r\n"
			+ "        \"SkipMultipleSignatureTypesAndBatchSigningDialogIfBatchSigningPossible\": true\r\n"
			+ "      },\r\n"
			+ "      \"VisibleAreaOptions\": {\r\n"
			+ "        \"AllowedDomain\": \"string\",\r\n"
			+ "        \"Enabled\": true\r\n"
			+ "      },\r\n"
			+ "      \"ShowStartGuidingHint\": true,\r\n"
			+ "      \"ShowStatusBar\": true,\r\n"
			+ "      \"ShowZoomButtons\": true,\r\n"
			+ "      \"ShowNoGeolocationWarning\": true,\r\n"
			+ "      \"AutoStartGuiding\": true,\r\n"
			+ "      \"ShowPageGap\": true,\r\n"
			+ "      \"ShowPageNavigationButtons\": true,\r\n"
			+ "      \"ShowFinishPossibleHint\": true,\r\n"
			+ "      \"SkipRejectConfirmDialog\": true,\r\n"
			+ "      \"BatchSigningType\": \"Basic\",\r\n"
			+ "      \"BatchSigningDisableNextButtonUntilDialogScrolledToBottom\": true\r\n"
			+ "    },\r\n"
			+ "    \"SignatureConfigurations\": [\r\n"
			+ "      {\r\n"
			+ "        \"SpcId\": \"string\",\r\n"
			+ "        \"PdfSignatureProperties\": {\r\n"
			+ "          \"PdfAConformant\": true,\r\n"
			+ "          \"PAdESPart4Compliant\": true,\r\n"
			+ "          \"IncludeSigningCertificateChain\": true,\r\n"
			+ "          \"SigningCertificateRevocationInformationIncludeMode\": \"DoNotInclude\",\r\n"
			+ "          \"SignatureTimestampData\": {\r\n"
			+ "            \"Uri\": \"string\",\r\n"
			+ "            \"Username\": \"string\",\r\n"
			+ "            \"Password\": \"string\",\r\n"
			+ "            \"SignatureHashAlgorithm\": \"Sha1\",\r\n"
			+ "            \"AuthenticationCertifiateDescriptor\": {\r\n"
			+ "              \"Identifier\": \"string\",\r\n"
			+ "              \"Type\": \"string\"\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"EnableEutlVerification\": true,\r\n"
			+ "          \"EnableValidateSigningCertificateName\": true,\r\n"
			+ "          \"SigningCertificateNameRegex\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"PdfSignatureCryptographicData\": {\r\n"
			+ "          \"SignatureHashAlgorithm\": \"Sha256\",\r\n"
			+ "          \"SigningCertificateDescriptor\": {\r\n"
			+ "            \"Identifier\": \"a653a2f2daf7353b8047ec9f537cdadd8e73ad92\",\r\n"
			+ "            \"Type\": \"Sha1Thumbprint\",\r\n"
			+ "            \"Csp\": \"Default\"\r\n"
			+ "          }\r\n"
			+ "        },\r\n"
			+ "        \"CertificateFilter\": {\r\n"
			+ "          \"KeyUsages\": [\r\n"
			+ "            \"string\"\r\n"
			+ "          ],\r\n"
			+ "          \"ThumbPrints\": [\r\n"
			+ "            \"string\"\r\n"
			+ "          ],\r\n"
			+ "          \"RootThumbPrints\": [\r\n"
			+ "            \"string\"\r\n"
			+ "          ]\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    ],\r\n"
			+ "    \"SigStringParsingConfiguration\": {\r\n"
			+ "      \"SigStringsForParsings\": [\r\n"
			+ "        {\r\n"
			+ "          \"StartPattern\": \"`sig\",\r\n"
			+ "          \"EndPattern\": \"`\",\r\n"
			+ "          \"ClearSigString\": true,\r\n"
			+ "          \"SearchEntireWordOnly\": true\r\n"
			+ "        }\r\n"
			+ "      ]\r\n"
			+ "    },\r\n"
			+ "    \"LinkParsingConfiguration\": {\r\n"
			+ "      \"ParsePdfGoToLinks\": true,\r\n"
			+ "      \"ParseHyperlinks\": true,\r\n"
			+ "      \"ExtractHyperlinksFromText\": true\r\n"
			+ "    },\r\n"
			+ "    \"GeneralPolicies\": {\r\n"
			+ "      \"AllowSaveDocument\": true,\r\n"
			+ "      \"AllowSaveAuditTrail\": true,\r\n"
			+ "      \"AllowRotatingPages\": true,\r\n"
			+ "      \"AllowAppendFileToWorkstep\": true,\r\n"
			+ "      \"AllowAppendTaskToWorkstep\": true,\r\n"
			+ "      \"AllowEmailDocument\": true,\r\n"
			+ "      \"AllowPrintDocument\": true,\r\n"
			+ "      \"AllowFinishWorkstep\": true,\r\n"
			+ "      \"AllowRejectWorkstep\": true,\r\n"
			+ "      \"AllowRejectWorkstepDelegation\": true,\r\n"
			+ "      \"AllowUndoLastAction\": true,\r\n"
			+ "      \"AllowColorizePdfForms\": true,\r\n"
			+ "      \"AllowAdhocPdfAttachments\": true,\r\n"
			+ "      \"AllowAdhocSignatures\": true,\r\n"
			+ "      \"AllowAdhocStampings\": true,\r\n"
			+ "      \"AllowAdhocFreeHandAnnotations\": true,\r\n"
			+ "      \"AllowAdhocTypewriterAnnotations\": true,\r\n"
			+ "      \"AllowAdhocPictureAnnotations\": true,\r\n"
			+ "      \"AllowAdhocPdfPageAppending\": true,\r\n"
			+ "      \"AllowReloadOfFinishedWorkstep\": true\r\n"
			+ "    },\r\n"
			+ "    \"FinalizeActions\": {\r\n"
			+ "      \"FinalizeActionList\": [\r\n"
			+ "\r\n"
			+ "      ]\r\n"
			+ "    },\r\n"
			+ "    \"TransactionCodeConfigurations\": [\r\n"
			+ "      {\r\n"
			+ "        \"Id\": \"string\",\r\n"
			+ "        \"HashAlgorithmIdentifier\": \"Sha1\",\r\n"
			+ "        \"Texts\": [\r\n"
			+ "          {\r\n"
			+ "            \"Language\": \"string\",\r\n"
			+ "            \"Value\": \"string\"\r\n"
			+ "          }\r\n"
			+ "        ]\r\n"
			+ "      }\r\n"
			+ "    ]\r\n"
			+ "  },\r\n"
			+ "  \"PrepareSendEnvelopeStepsDescriptor\": {\r\n"
			+ "    \"ClearFieldMarkupString\": true\r\n"
			+ "  }\r\n"
			+ "}\r\n"
			+ "";

	public static String getRequest() {
		return request;
	}

	public static void setSspFileId(String id) {
		prepareEnvelope.request = "{\r\n"
				+ "  \"SspFileIds\":[\""+id+"\"],\r\n"
				+ "  \"AdHocWorkstepConfiguration\": {\r\n"
				+ "    \"WorkstepLabel\": \"workstepLabel\",\r\n"
				+ "    \"SmallTextZoomFactorPercent\": 100,\r\n"
				+ "    \"WorkstepTimeToLiveInMinutes\": 100000,\r\n"
				+ "    \"FinishAction\": {\r\n"
				+ "      \"ServerActions\": [\r\n"
				+ "        {\r\n"
				+ "          \"CallSynchronous\": true\r\n"
				+ "        }\r\n"
				+ "      ],\r\n"
				+ "      \"ClientActions\": [\r\n"
				+ "        {\r\n"
				+ "          \"RemoveDocumentFromRecentDocumentList\": true,\r\n"
				+ "          \"CallClientActionOnlyAfterSuccessfulSync\": true,\r\n"
				+ "          \"ClientName\": \"string\",\r\n"
				+ "          \"CloseApp\": true,\r\n"
				+ "          \"Action\": \"string\"\r\n"
				+ "        }\r\n"
				+ "      ]\r\n"
				+ "    },\r\n"
				+ "    \"NoSequenceEnforced\": false,\r\n"
				+ "    \"SigTemplate\": {\r\n"
				+ "      \"Size\": {\r\n"
				+ "        \"Height\": 68,\r\n"
				+ "        \"Width\": 171\r\n"
				+ "      },\r\n"
				+ "      \"AllowedSignatureTypes\": [\r\n"
				+ "        {\r\n"
				+ "          \"TrModType\": \"TransactionCodeSenderPlugin\",\r\n"
				+ "          \"TrValidityInSeconds\": 300,\r\n"
				+ "          \"Ly\": \"simpleTransactionCodeSms\",\r\n"
				+ "          \"TrConfId\": \"otpSignatureSmsText\",\r\n"
				+ "          \"IsPhoneNumberRequired\": true,\r\n"
				+ "          \"Id\": \"e80a4c7f-3492-4a56-ac47-1dec59dfb7ad\",\r\n"
				+ "          \"DiscriminatorType\": \"SigTypeTransactionCode\",\r\n"
				+ "          \"Preferred\": false,\r\n"
				+ "          \"StampImprintConfiguration\":\r\n"
				+ "          {\r\n"
				+ "            \"DisplayExtraInformation\": true,\r\n"
				+ "            \"DisplayEmail\": true,\r\n"
				+ "            \"DisplayIp\": true,\r\n"
				+ "            \"DisplayName\": true,\r\n"
				+ "            \"DisplaySignatureDate\": true,\r\n"
				+ "            \"FontFamily\": \"Times New Roman\",\r\n"
				+ "            \"FontSize\": 10,\r\n"
				+ "            \"OverrideLegacyStampImprint\": true,\r\n"
				+ "            \"DisplayTransactionId\": true,\r\n"
				+ "            \"DisplayTransaktionToken\": true,\r\n"
				+ "            \"DisplayPhoneNumber\": true\r\n"
				+ "          }\r\n"
				+ "        }\r\n"
				+ "      ]\r\n"
				+ "    },\r\n"
				+ "    \"ParseFormFields\": {\r\n"
				+ "      \"MapRequiredFieldsToRequiredTask\": true,\r\n"
				+ "      \"FormsGrouping\": \"PerPage\",\r\n"
				+ "      \"ReturnSimplifiedConfig\": true,\r\n"
				+ "      \"AddKeepExistingValueFlag\": true,\r\n"
				+ "      \"ParseFormField\": true\r\n"
				+ "    },\r\n"
				+ "    \"AdhocPolicies\": {\r\n"
				+ "      \"AllowModificationsAfterSignature\": true\r\n"
				+ "    },\r\n"
				+ "    \"ViewerPreferences\": {\r\n"
				+ "      \"ShowPageNavigationBar\": true,\r\n"
				+ "      \"ShowThumbnails\": true,\r\n"
				+ "      \"SkipFinishConfirmDialog\": true,\r\n"
				+ "      \"SkipDocumentDialog\": true,\r\n"
				+ "      \"ShowImagesInFullWidth\": true,\r\n"
				+ "      \"DisableGeolocation\": true,\r\n"
				+ "      \"ShowDocumentDownloadDialogAfterAutomaticFinish\": true,\r\n"
				+ "      \"AttachmentsMaxFileSize\": 0,\r\n"
				+ "      \"SkipPreviewImageOnDisposableCertificate\": true,\r\n"
				+ "      \"LoadCustomJs\": true,\r\n"
				+ "      \"AllowCustomButtons\": true,\r\n"
				+ "      \"GuidingBehavior\": \"GuideOnlyRequiredTasks\",\r\n"
				+ "      \"FormFieldsGuidingBehavior\": \"AllowSubmitAlways\",\r\n"
				+ "      \"ShowVersionNumber\": true,\r\n"
				+ "      \"EnableWarningPopupOnLeave\": true,\r\n"
				+ "      \"WarningPopupDisplayAfter\": \"FillOrSignField\",\r\n"
				+ "      \"FinishWorkstepOnOpen\": true,\r\n"
				+ "      \"AutoFinishAfterRequiredTasksDone\": true,\r\n"
				+ "      \"GuidingBehaviorOnFinishedTask\": \"NoMove\",\r\n"
				+ "      \"SkipThankYouDialog\": true,\r\n"
				+ "      \"NativeAppsUrlScheme\": \"string\",\r\n"
				+ "      \"DocumentViewingMode\": \"EndlessPaperAllDocuments\",\r\n"
				+ "      \"ThumbnailMode\": \"ShowAllPages\",\r\n"
				+ "      \"ShowTopBar\": true,\r\n"
				+ "      \"DisplayRejectButtonInTopBar\": true,\r\n"
				+ "      \"MultipleSignatureTypesAndBatchSigningSettings\": {\r\n"
				+ "        \"IsUseBatchSigningCheckedByDefault\": true,\r\n"
				+ "        \"IsRememberSignatureTypeCheckedByDefault\": true,\r\n"
				+ "        \"IsRememberBatchSigningDecisionCheckedByDefault\": true,\r\n"
				+ "        \"SkipMultipleSignatureTypesAndBatchSigningDialogIfBatchSigningPossible\": true\r\n"
				+ "      },\r\n"
				+ "      \"VisibleAreaOptions\": {\r\n"
				+ "        \"AllowedDomain\": \"string\",\r\n"
				+ "        \"Enabled\": true\r\n"
				+ "      },\r\n"
				+ "      \"ShowStartGuidingHint\": true,\r\n"
				+ "      \"ShowStatusBar\": true,\r\n"
				+ "      \"ShowZoomButtons\": true,\r\n"
				+ "      \"ShowNoGeolocationWarning\": true,\r\n"
				+ "      \"AutoStartGuiding\": true,\r\n"
				+ "      \"ShowPageGap\": true,\r\n"
				+ "      \"ShowPageNavigationButtons\": true,\r\n"
				+ "      \"ShowFinishPossibleHint\": true,\r\n"
				+ "      \"SkipRejectConfirmDialog\": true,\r\n"
				+ "      \"BatchSigningType\": \"Basic\",\r\n"
				+ "      \"BatchSigningDisableNextButtonUntilDialogScrolledToBottom\": true\r\n"
				+ "    },\r\n"
				+ "    \"SignatureConfigurations\": [\r\n"
				+ "      {\r\n"
				+ "        \"SpcId\": \"string\",\r\n"
				+ "        \"PdfSignatureProperties\": {\r\n"
				+ "          \"PdfAConformant\": true,\r\n"
				+ "          \"PAdESPart4Compliant\": true,\r\n"
				+ "          \"IncludeSigningCertificateChain\": true,\r\n"
				+ "          \"SigningCertificateRevocationInformationIncludeMode\": \"DoNotInclude\",\r\n"
				+ "          \"SignatureTimestampData\": {\r\n"
				+ "            \"Uri\": \"string\",\r\n"
				+ "            \"Username\": \"string\",\r\n"
				+ "            \"Password\": \"string\",\r\n"
				+ "            \"SignatureHashAlgorithm\": \"Sha1\",\r\n"
				+ "            \"AuthenticationCertifiateDescriptor\": {\r\n"
				+ "              \"Identifier\": \"string\",\r\n"
				+ "              \"Type\": \"string\"\r\n"
				+ "            }\r\n"
				+ "          },\r\n"
				+ "          \"EnableEutlVerification\": true,\r\n"
				+ "          \"EnableValidateSigningCertificateName\": true,\r\n"
				+ "          \"SigningCertificateNameRegex\": \"string\"\r\n"
				+ "        },\r\n"
				+ "        \"PdfSignatureCryptographicData\": {\r\n"
				+ "          \"SignatureHashAlgorithm\": \"Sha256\",\r\n"
				+ "          \"SigningCertificateDescriptor\": {\r\n"
				+ "            \"Identifier\": \"a653a2f2daf7353b8047ec9f537cdadd8e73ad92\",\r\n"
				+ "            \"Type\": \"Sha1Thumbprint\",\r\n"
				+ "            \"Csp\": \"Default\"\r\n"
				+ "          }\r\n"
				+ "        },\r\n"
				+ "        \"CertificateFilter\": {\r\n"
				+ "          \"KeyUsages\": [\r\n"
				+ "            \"string\"\r\n"
				+ "          ],\r\n"
				+ "          \"ThumbPrints\": [\r\n"
				+ "            \"string\"\r\n"
				+ "          ],\r\n"
				+ "          \"RootThumbPrints\": [\r\n"
				+ "            \"string\"\r\n"
				+ "          ]\r\n"
				+ "        }\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"SigStringParsingConfiguration\": {\r\n"
				+ "      \"SigStringsForParsings\": [\r\n"
				+ "        {\r\n"
				+ "          \"StartPattern\": \"`sig\",\r\n"
				+ "          \"EndPattern\": \"`\",\r\n"
				+ "          \"ClearSigString\": true,\r\n"
				+ "          \"SearchEntireWordOnly\": true\r\n"
				+ "        }\r\n"
				+ "      ]\r\n"
				+ "    },\r\n"
				+ "    \"LinkParsingConfiguration\": {\r\n"
				+ "      \"ParsePdfGoToLinks\": true,\r\n"
				+ "      \"ParseHyperlinks\": true,\r\n"
				+ "      \"ExtractHyperlinksFromText\": true\r\n"
				+ "    },\r\n"
				+ "    \"GeneralPolicies\": {\r\n"
				+ "      \"AllowSaveDocument\": true,\r\n"
				+ "      \"AllowSaveAuditTrail\": true,\r\n"
				+ "      \"AllowRotatingPages\": true,\r\n"
				+ "      \"AllowAppendFileToWorkstep\": true,\r\n"
				+ "      \"AllowAppendTaskToWorkstep\": true,\r\n"
				+ "      \"AllowEmailDocument\": true,\r\n"
				+ "      \"AllowPrintDocument\": true,\r\n"
				+ "      \"AllowFinishWorkstep\": true,\r\n"
				+ "      \"AllowRejectWorkstep\": true,\r\n"
				+ "      \"AllowRejectWorkstepDelegation\": true,\r\n"
				+ "      \"AllowUndoLastAction\": true,\r\n"
				+ "      \"AllowColorizePdfForms\": true,\r\n"
				+ "      \"AllowAdhocPdfAttachments\": true,\r\n"
				+ "      \"AllowAdhocSignatures\": true,\r\n"
				+ "      \"AllowAdhocStampings\": true,\r\n"
				+ "      \"AllowAdhocFreeHandAnnotations\": true,\r\n"
				+ "      \"AllowAdhocTypewriterAnnotations\": true,\r\n"
				+ "      \"AllowAdhocPictureAnnotations\": true,\r\n"
				+ "      \"AllowAdhocPdfPageAppending\": true,\r\n"
				+ "      \"AllowReloadOfFinishedWorkstep\": true\r\n"
				+ "    },\r\n"
				+ "    \"FinalizeActions\": {\r\n"
				+ "      \"FinalizeActionList\": [\r\n"
				+ "\r\n"
				+ "      ]\r\n"
				+ "    },\r\n"
				+ "    \"TransactionCodeConfigurations\": [\r\n"
				+ "      {\r\n"
				+ "        \"Id\": \"string\",\r\n"
				+ "        \"HashAlgorithmIdentifier\": \"Sha1\",\r\n"
				+ "        \"Texts\": [\r\n"
				+ "          {\r\n"
				+ "            \"Language\": \"string\",\r\n"
				+ "            \"Value\": \"string\"\r\n"
				+ "          }\r\n"
				+ "        ]\r\n"
				+ "      }\r\n"
				+ "    ]\r\n"
				+ "  },\r\n"
				+ "  \"PrepareSendEnvelopeStepsDescriptor\": {\r\n"
				+ "    \"ClearFieldMarkupString\": true\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "";
	}
	
	
	
}
