package com.Contum.Integration.models;

public class sendEnvelope2s extends sendEnvelopeBase{
	

	public static String r1pin;
	public static String r2pin;

	
	
	public static String getR1pin() {
		return r1pin;
	}
	public static void setR1pin(String r1pin) {
		sendEnvelope2s.r1pin = r1pin;
	}
	public static String getR2pin() {
		return r2pin;
	}
	public static void setR2pin(String r2pin) {
		sendEnvelope2s.r2pin = r2pin;
	}
	
	public static void setParameters(String envelopeName, String r1Email,String r1FirstName, String r1LastName,String r2Email,
			String r2FirstName, String r2LastName,String r1pin,String r2pin) {
		setEnvelopeName(envelopeName);
		setR1Email(r1Email);
		setR1FirstName(r1FirstName);
		setR1LastName(r1LastName);
		setR1pin(r1pin);
		setR2pin(r2pin);
		setR2Email(r2Email);
		setR2FirstName(r2FirstName);
		setR2LastName(r2LastName);
		
	}
	
	
	public static String getRequest() {
		return " {\r\n"
				+ "  \"SspFileIds\":[\""+sspFileId+"\"],\r\n"
				+ "\"SendEnvelopeDescription\": {\r\n"
				+ "  \"Name\":\""+envelopeName+"\",\r\n"
				+ "  \"EmailSubject\": \"Please sign the enclosed envelope\",\r\n"
				+ "  \"EmailBody\": \"Dear #RecipientFirstName# #RecipientLastName#\\n\\n#PersonalMessage#\\n\\nPlease sign the envelope #EnvelopeName#\\n\\nEnvelope will expire at #ExpirationDate#\",\r\n"
				+ "  \"DisplayedEmailSender\": \"\",\r\n"
				+ "  \"EnableReminders\": true,\r\n"
				+ "  \"FirstReminderDayAmount\": 5,\r\n"
				+ "  \"RecurrentReminderDayAmount\": 3,\r\n"
				+ "  \"BeforeExpirationDayAmount\": 3,\r\n"
				+ "  \"DaysUntilExpire\": 28,\r\n"
				+ "  \"CallbackUrl\": \"\",\r\n"
				+ "  \"StatusUpdateCallbackUrl\": \"\",\r\n"
				+ "  \"Steps\": [\r\n"
				+ "    {\r\n"
				+ "      \"OrderIndex\": 1,\r\n"
				+ "      \"Recipients\": [\r\n"
				+ "        {\r\n"
				+ "  \"Email\":\""+r1Email+"\",\r\n"
				+ "  \"FirstName\":\""+r1FirstName+"\",\r\n"
				+ "  \"LastName\":\""+r1LastName+"\",\r\n"
				+ "          \"LanguageCode\": \"en\",\r\n"
				+ "          \"EmailBodyExtra\": \"\",\r\n"
				+ "          \"DisableEmail\": false,\r\n"
				+ "          \"AddAndroidAppLink\": false,\r\n"
				+ "          \"AddIosAppLink\": false,\r\n"
				+ "          \"AddWindowsAppLink\": false,\r\n"
				+ "          \"AllowDelegation\": true,\r\n"
				+ "          \"SkipExternalDataValidation\": false,\r\n"
				+ "          \"AuthenticationMethods\": [\r\n"
				+ "			{\r\n"
				+ "              \"Method\": \"Pin\",\r\n"
				+ "  \"Parameter\":\""+r1pin+"\",\r\n"
				+ "			}\r\n"
				+ "		]\r\n"
				+ "        }\r\n"
				+ "      ],\r\n"
				+ "      \"EmailBodyExtra\": \"\",\r\n"
				+ "      \"RecipientType\": \"Signer\",\r\n"
				+ "      \"WorkstepConfiguration\": {\r\n"
				+ "        \"WorkstepLabel\": \"test\",\r\n"
				+ "        \"SmallTextZoomFactorPercent\": 100,\r\n"
				+ "        \"FinishAction\": {\r\n"
				+ "          \"ServerActions\": [],\r\n"
				+ "          \"ClientActions\": []\r\n"
				+ "        },\r\n"
				+ "		 \"SenderInformation\": {\r\n"
				+ "                  \"UserInformation\": {\r\n"
				+ "                     \"FirstName\": \"Bence\",\r\n"
				+ "                     \"LastName\": \"Katona\",\r\n"
				+ "                     \"EMail\": \"gabor.katona@contum.hu\"\r\n"
				+ "                  }\r\n"
				+ "               },\r\n"
				+ "               \"ReceiverInformation\": {\r\n"
				+ "                  \"UserInformation\": {\r\n"
				+ "                     \"FirstName\": \"string\",\r\n"
				+ "                     \"LastName\": \"string\",\r\n"
				+ "                     \"EMail\": \"string\"\r\n"
				+ "                  }\r\n"
				+ "               },\r\n"
				+ "        \r\n"
				+ "          \"TransactionCodePushPluginData\": [],\r\n"
				+ "        \r\n"
				+ "       \r\n"
				+ "        \"TransactionCodeConfigurations\": [\r\n"
				+ "          {\r\n"
				+ "          }\r\n"
				+ "        ],\r\n"
				+ "        \"SignatureConfigurations\": [],\r\n"
				+ "        \"ViewerPreferences\": {\r\n"
				+ "          \"FinishWorkstepOnOpen\": false,\r\n"
				+ "          \"VisibleAreaOptions\": {\r\n"
				+ "            \"AllowedDomain\": \"*\",\r\n"
				+ "            \"Enabled\": false\r\n"
				+ "          }\r\n"
				+ "        },\r\n"
				+ "        \"Policy\": {\r\n"
				+ "		\"GeneralPolicies\": {\r\n"
				+ "			\"AllowSaveDocument\": true,\r\n"
				+ "			\"AllowSaveAuditTrail\": true,\r\n"
				+ "			\"AllowRotatingPages\": true,\r\n"
				+ "			\"AllowAppendFileToWorkstep\": true,\r\n"
				+ "			\"AllowAppendTaskToWorkstep\": true,\r\n"
				+ "			\"AllowEmailDocument\": true,\r\n"
				+ "			\"AllowPrintDocument\": true,\r\n"
				+ "			\"AllowFinishWorkstep\": true,\r\n"
				+ "			\"AllowRejectWorkstep\": true,\r\n"
				+ "			\"AllowRejectWorkstepDelegation\": true,\r\n"
				+ "			\"AllowUndoLastAction\": true,\r\n"
				+ "			\"AllowColorizePdfForms\": true,\r\n"
				+ "			\"AllowAdhocPdfAttachments\": true,\r\n"
				+ "			\"AllowAdhocSignatures\": true,\r\n"
				+ "			\"AllowAdhocStampings\": true,\r\n"
				+ "			\"AllowAdhocFreeHandAnnotations\": true,\r\n"
				+ "			\"AllowAdhocTypewriterAnnotations\": true,\r\n"
				+ "			\"AllowAdhocPictureAnnotations\": true,\r\n"
				+ "			\"AllowAdhocPdfPageAppending\": true,\r\n"
				+ "			\"AllowReloadOfFinishedWorkstep\": true\r\n"
				+ "		},\r\n"
				+ "          \r\n"
				+ "        \"WorkstepTasks\": {\r\n"
				+ "             \"PictureAnnotationMinResolution\": 0,\r\n"
				+ "            \"PictureAnnotationMaxResolution\": 0,\r\n"
				+ "            \"PictureAnnotationColorDepth\": \"Color16M\",\r\n"
				+ "            \"SequenceMode\": \"NoSequenceEnforced\",\r\n"
				+ "            \"PositionUnits\": \"PdfUnits\",\r\n"
				+ "            \"ReferenceCorner\": \"Lower_Left\",\r\n"
				+ "            \"Tasks\": [\r\n"
				+ "              {\r\n"
				+ "                \"PositionPage\": 1,\r\n"
				+ "                \"Position\": {\r\n"
				+ "                   \"PositionX\": 40,\r\n"
				+ "                  \"PositionY\": 742\r\n"
				+ "                },\r\n"
				+ "                \"Size\": {\r\n"
				+ "                  \"Height\": 80.0,\r\n"
				+ "                  \"Width\": 190.0\r\n"
				+ "                },\r\n"
				+ "                \"AdditionalParameters\": [\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"enabled\",\r\n"
				+ "                    \"Value\": \"1\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"positioning\",\r\n"
				+ "                    \"Value\": \"onPage\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"req\",\r\n"
				+ "                    \"Value\": \"1\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"fd\",\r\n"
				+ "                    \"Value\": \"\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"fd_dateformat\",\r\n"
				+ "                    \"Value\": \"dd-MM-yyyy HH:mm:ss\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"fd_timezone\",\r\n"
				+ "                    \"Value\": \"datetimeutc+1\"\r\n"
				+ "                  }\r\n"
				+ "                ],\r\n"
				+ "                \"AllowedSignatureTypes\": [\r\n"
				+ "                 	 {\r\n"
				+ "                    \"AllowedCapturingMethod\": \"Click2Sign\",\r\n"
				+ "                    \"StampImprintConfiguration\": {\r\n"
				+ "                       \"DisplayExtraInformation\": true,\r\n"
				+ "                      \"DisplayEmail\": true,\r\n"
				+ "                      \"DisplayIp\": true,\r\n"
				+ "                      \"DisplayName\": true,\r\n"
				+ "                      \"DisplaySignatureDate\": true,\r\n"
				+ "                      \"FontFamily\": \"Times New Roman\",\r\n"
				+ "                      \"FontSize\": 11.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Id\": \"d63ec0d5-a2ca-46d9-9c73-7bd8d91aa4ea\",\r\n"
				+ "                    \"DiscriminatorType\": \"SigTypeClick2Sign\",\r\n"
				+ "                    \"Preferred\": true\r\n"
				+ "                  }\r\n"
				+ "                ],\r\n"
				+ "                \"UseTimestamp\": false,\r\n"
				+ "                \"IsRequired\": true,\r\n"
				+ "                \"Id\": \"1#XyzmoDuplicateIdSeperator#Signature_94816166-6b59-1cc1-de9b-285633162aef\",\r\n"
				+ "                \"DisplayName\": \"\",\r\n"
				+ "                \"DocRefNumber\": 1,\r\n"
				+ "                \"DiscriminatorType\": \"Signature\"\r\n"
				+ "              }\r\n"
				+ "            ]\r\n"
				+ "          }\r\n"
				+ "        }\r\n"
				+ "      },\r\n"
				+ "\r\n"
				+ "      \"DocumentOptions\": [\r\n"
				+ "        {\r\n"
				+ "          \"DocumentReference\": \"1\",\r\n"
				+ "          \"IsHidden\": false\r\n"
				+ "        }\r\n"
				+ "      ],\r\n"
				+ "      \"UseDefaultAgreements\": true\r\n"
				+ "    },\r\n"
				+ "   {\r\n"
				+ "      \"OrderIndex\": 2,\r\n"
				+ "      \"Recipients\": [\r\n"
				+ "        {\r\n"
				+ "  \"Email\":\""+r2Email+"\",\r\n"
				+ "          \"FirstName\": \""+r2FirstName+"\",\r\n"
				+ "          \"LastName\": \""+r2LastName+"\",\r\n"
				+ "          \"LanguageCode\": \"en\",\r\n"
				+ "          \"EmailBodyExtra\": \"\",\r\n"
				+ "          \"DisableEmail\": false,\r\n"
				+ "          \"AddAndroidAppLink\": true,\r\n"
				+ "          \"AddIosAppLink\": false,\r\n"
				+ "          \"AddWindowsAppLink\": false,\r\n"
				+ "          \"AllowDelegation\": true,\r\n"
				+ "          \"SkipExternalDataValidation\": false,\r\n"
				+ "          \"AuthenticationMethods\": [\r\n"
				+ "		{\r\n"
				+ "              \"Method\": \"Pin\",\r\n"
				+ "  \"Parameter\":\""+r2pin+"\",\r\n"
				+ "			}\r\n"
				+ "		]\r\n"
				+ "        }\r\n"
				+ "      ],\r\n"
				+ "      \"EmailBodyExtra\": \"\",\r\n"
				+ "      \"RecipientType\": \"Signer\",\r\n"
				+ "      \"WorkstepConfiguration\": {\r\n"
				+ "        \"WorkstepLabel\": \"test\",\r\n"
				+ "        \"SmallTextZoomFactorPercent\": 100,\r\n"
				+ "        \"FinishAction\": {\r\n"
				+ "          \"ServerActions\": [],\r\n"
				+ "          \"ClientActions\": []\r\n"
				+ "        },\r\n"
				+ "		 \"SenderInformation\": {\r\n"
				+ "                  \"UserInformation\": {\r\n"
				+ "  				     \"FirstName\": \"string\",\r\n"
				+ "					 \"LastName\":\"string\",\r\n"
				+ "                     \"EMail\": \"gabor.katona@contum.hu\"\r\n"
				+ "                  }\r\n"
				+ "               },\r\n"
				+ "               \"ReceiverInformation\": {\r\n"
				+ "                  \"UserInformation\": {\r\n"
				+ "  \"FirstName\":\"string\",\r\n"
				+ "  \"LastName\":\"string\",\r\n"
				+ "                     \"EMail\": \"string\"\r\n"
				+ "                  }\r\n"
				+ "               },\r\n"
				+ "        \r\n"
				+ "          \"TransactionCodePushPluginData\": [],\r\n"
				+ "        \r\n"
				+ "       \r\n"
				+ "        \"TransactionCodeConfigurations\": [\r\n"
				+ "          {\r\n"
				+ "          }\r\n"
				+ "        ],\r\n"
				+ "        \"SignatureConfigurations\": [],\r\n"
				+ "        \"ViewerPreferences\": {\r\n"
				+ "          \"FinishWorkstepOnOpen\": false,\r\n"
				+ "          \"VisibleAreaOptions\": {\r\n"
				+ "            \"AllowedDomain\": \"*\",\r\n"
				+ "            \"Enabled\": false\r\n"
				+ "          }\r\n"
				+ "        },\r\n"
				+ "        \"Policy\": {\r\n"
				+ "		\"GeneralPolicies\": {\r\n"
				+ "			\"AllowSaveDocument\": true,\r\n"
				+ "			\"AllowSaveAuditTrail\": true,\r\n"
				+ "			\"AllowRotatingPages\": true,\r\n"
				+ "			\"AllowAppendFileToWorkstep\": true,\r\n"
				+ "			\"AllowAppendTaskToWorkstep\": true,\r\n"
				+ "			\"AllowEmailDocument\": true,\r\n"
				+ "			\"AllowPrintDocument\": true,\r\n"
				+ "			\"AllowFinishWorkstep\": true,\r\n"
				+ "			\"AllowRejectWorkstep\": true,\r\n"
				+ "			\"AllowRejectWorkstepDelegation\": true,\r\n"
				+ "			\"AllowUndoLastAction\": true,\r\n"
				+ "			\"AllowColorizePdfForms\": true,\r\n"
				+ "			\"AllowAdhocPdfAttachments\": true,\r\n"
				+ "			\"AllowAdhocSignatures\": true,\r\n"
				+ "			\"AllowAdhocStampings\": true,\r\n"
				+ "			\"AllowAdhocFreeHandAnnotations\": true,\r\n"
				+ "			\"AllowAdhocTypewriterAnnotations\": true,\r\n"
				+ "			\"AllowAdhocPictureAnnotations\": true,\r\n"
				+ "			\"AllowAdhocPdfPageAppending\": true,\r\n"
				+ "			\"AllowReloadOfFinishedWorkstep\": true\r\n"
				+ "		},\r\n"
				+ "          \r\n"
				+ "        \"WorkstepTasks\": {\r\n"
				+ "             \"PictureAnnotationMinResolution\": 0,\r\n"
				+ "            \"PictureAnnotationMaxResolution\": 0,\r\n"
				+ "            \"PictureAnnotationColorDepth\": \"Color16M\",\r\n"
				+ "            \"SequenceMode\": \"NoSequenceEnforced\",\r\n"
				+ "            \"PositionUnits\": \"PdfUnits\",\r\n"
				+ "            \"ReferenceCorner\": \"Lower_Left\",\r\n"
				+ "            \"Tasks\": [\r\n"
				+ "              {\r\n"
				+ "                \"PositionPage\": 1,\r\n"
				+ "                \"Position\": {\r\n"
				+ "                   \"PositionX\": 382,\r\n"
				+ "                  \"PositionY\": 742\r\n"
				+ "                },\r\n"
				+ "                \"Size\": {\r\n"
				+ "                  \"Height\": 80.0,\r\n"
				+ "                  \"Width\": 190.0\r\n"
				+ "                },\r\n"
				+ "                \"AdditionalParameters\": [\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"enabled\",\r\n"
				+ "                    \"Value\": \"1\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"positioning\",\r\n"
				+ "                    \"Value\": \"onPage\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"req\",\r\n"
				+ "                    \"Value\": \"1\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"fd\",\r\n"
				+ "                    \"Value\": \"\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"fd_dateformat\",\r\n"
				+ "                    \"Value\": \"dd-MM-yyyy HH:mm:ss\"\r\n"
				+ "                  },\r\n"
				+ "                  {\r\n"
				+ "                    \"Key\": \"fd_timezone\",\r\n"
				+ "                    \"Value\": \"datetimeutc+1\"\r\n"
				+ "                  }\r\n"
				+ "                ],\r\n"
				+ "                \"AllowedSignatureTypes\": [\r\n"
				+ "                  	 {\r\n"
				+ "                    \"AllowedCapturingMethod\": \"Click2Sign\",\r\n"
				+ "                    \"StampImprintConfiguration\": {\r\n"
				+ "                      \"DisplayExtraInformation\": true,\r\n"
				+ "                      \"DisplayEmail\": true,\r\n"
				+ "                      \"DisplayIp\": true,\r\n"
				+ "                      \"DisplayName\": true,\r\n"
				+ "                      \"DisplaySignatureDate\": true,\r\n"
				+ "                      \"FontFamily\": \"Times New Roman\",\r\n"
				+ "                      \"FontSize\": 11.0\r\n"
				+ "                    },\r\n"
				+ "                    \"Id\": \"d63ec0d5-a2ca-46d9-9c73-7bd8d91aa4ea\",\r\n"
				+ "                    \"DiscriminatorType\": \"SigTypeClick2Sign\",\r\n"
				+ "                    \"Preferred\": true\r\n"
				+ "                  }\r\n"
				+ "                ],\r\n"
				+ "                \"UseTimestamp\": false,\r\n"
				+ "                \"IsRequired\": true,\r\n"
				+ "                \"Id\": \"2#XyzmoDuplicateIdSeperator#Signature_94816166-6b59-1cc1-de9b-131333162aef\",\r\n"
				+ "                \"DisplayName\": \"\",\r\n"
				+ "                \"DocRefNumber\": 1,\r\n"
				+ "                \"DiscriminatorType\": \"Signature\"\r\n"
				+ "              }\r\n"
				+ "            ]\r\n"
				+ "          }\r\n"
				+ "        }\r\n"
				+ "      },\r\n"
				+ "\r\n"
				+ "      \"DocumentOptions\": [\r\n"
				+ "        {\r\n"
				+ "          \"DocumentReference\": \"1\",\r\n"
				+ "          \"IsHidden\": false\r\n"
				+ "        }\r\n"
				+ "      ],\r\n"
				+ "      \"UseDefaultAgreements\": true\r\n"
				+ "    }\r\n"
				+ "      ],\r\n"
				+ "\r\n"
				+ "  \"AddFormFields\": {\r\n"
				+ "    \"Forms\": {}\r\n"
				+ "  },\r\n"
				+ "  \"OverrideFormFieldValues\": {\r\n"
				+ "    \"Forms\": {}\r\n"
				+ "  },\r\n"
				+ "  \"AttachSignedDocumentsToEnvelopeLog\": false\r\n"
				+ "}\r\n"
				+ "}\r\n"
				+ "";
	}

}
